### ISSUE TITLE
Can't go install cmd/libasciidoc

### ISSUE THREAD

**Issue by pjanx** [bytesparadise/libasciidoc#1076]
```
$ go install github.com/bytesparadise/libasciidoc/cmd/libasciidoc@latest
go: github.com/bytesparadise/libasciidoc/cmd/libasciidoc@latest (in github.com/bytesparadise/libasciidoc@v0.7.0):
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.
```
```
// include support for disabling unexported fields
// TODO: still needed?
replace github.com/davecgh/go-spew => github.com/flw-cn/go-spew v1.1.2-0.20200624141737-10fccbfd0b23
```
More of a convenience issue.

**Comment by xcoulon** [comment]
thanks for reporting this @pjanx! 

For now, the `github.com/davecgh/go-spew => github.com/flw-cn/go-spew` replacement is still needed (I agree that the `TODO?` comment is misleading), and it works fine if you run `make install`.

Also, the [Installation](https://github.com/bytesparadise/libasciidoc#installation) section of the README suggests to use `make install`, so I'm going to close this issue (at least for now)
