### ISSUE TITLE
Underscores break bold formatting

### ISSUE THREAD

**Issue by pjanx** [bytesparadise/libasciidoc#1078]
```
*a_b* _c_
```
libasciidoc
```
<div class="paragraph">
<p>*a_b* <em>c</em></p>
</div>
```
asciidoctor
```
<div class="paragraph">
<p><strong>a_b</strong> <em>c</em></p>
</div>
```
asciidoc
```
<div class="paragraph"><p><strong>a_b</strong> <em>c</em></p></div>
```

**Comment by xcoulon** [comment]
thanks for reporting this bug @pjanx, I'll look into it while I'm also working on #1077

**Comment by xcoulon** [comment]
sorry for the late response, @pjanx :/
this bug was fixed in https://github.com/bytesparadise/libasciidoc/commit/eecd0bb78e2f11932d9ca04d4dd831cc1356c66c, and I added a couple of tests in https://github.com/bytesparadise/libasciidoc/pull/1082 to verify that
