### ISSUE TITLE
Document build dependencies

### ISSUE THREAD

**Issue by etsauer** [bytesparadise/libasciidoc#152]
In order to get the `libasciidoc` cli binary installed, I had to do the following:

```
    $ go get -u github.com/mna/pigeon
    $ curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
    $ go get -u github.com/bytesparadise/libasciidoc
    $ cd $GOPATH/src/github.com/bytesparadise/libasciidoc
    $ make build
```

Ok to open a quick PR, updating the README with these changes?

**Comment by xcoulon** [comment]
hello @etsauer. Yes, sure, open a PR so we have those steps documented!
