### ISSUE TITLE
Extra leading spaces in literal paragraphs

### ISSUE THREAD

**Issue by pjanx** [bytesparadise/libasciidoc#188]
I'm not sure whether this is in any way related to #62 but
```
 abc
 def
 ghi
```
is transformed to
```
<pre>abc
 def
 ghi</pre>
```
The leading spaces [shouldn't be there](http://www.methods.co.nz/asciidoc/asciidoc.html#X85) for the 2nd, 3rd etc. line. Or at least they should be included on the 1st line as well for the time being. It looks pretty bad.

**Comment by xcoulon** [comment]
thanks for reporting this issue, @pjanx! I'll take care about trimming the leading spaces.

**Comment by xcoulon** [comment]
@pjanx issue should be fixed now:
````
> libasciidoc -s -o - tmp/test.adoc
<div class="literalblock">
<div class="content">
<pre>abc
def
ghi</pre>
</div>
</div>
````
Thanks again for reporting this issue, and feel free to reopen it if you find something wrong ;)
