### ISSUE TITLE
Support for explicit line breaks

### ISSUE THREAD

**Issue by pjanx** [bytesparadise/libasciidoc#189]
http://www.methods.co.nz/asciidoc/asciidoc.html#_line_breaks
```
abc +
def
```
should produce
```
<p>abc<br>def</p>
```

**Comment by xcoulon** [comment]
thanks for reporting this issue, @pjanx! I'll take care of it

**Comment by xcoulon** [comment]
@pjanx issue should be fixed now. Thanks again for reporting it, and feel free to reopen if you find anything wrong with regards to hard breaks ;)
