### ISSUE TITLE
PDF Support

### ISSUE THREAD

**Issue by jhinrichsen** [bytesparadise/libasciidoc#308]
Bonjour Xavier,

i wonder if you plan to include PDF support, or if this is out of scope for libasciidoc. My main reason to send out PDFs instead of HTML is that images are included.

Happy to see someone work on the Go version of Asciidoc, keep it up!

**Comment by xcoulon** [comment]
Guten Tag Jochen!

I have no plan to include PDF support in immediately since my current focus is on HTML5 so that libasciidoc can be included in Hugo, but the `pkg/renderer` pkg has some space for a `pdf` sub-package, so I may work on that in the future.
