### ISSUE TITLE
Use template delimiter with minus to remove spaces

### ISSUE THREAD

**Issue by xcoulon** [bytesparadise/libasciidoc#309]
see official doc on https://golang.org/pkg/text/template/#hdr-Text_and_spaces:

> if an action's left delimiter (by default "{{") is followed immediately by a minus sign and ASCII space character ("{{- "), all trailing white space is trimmed from the immediately preceding text. Similarly, if the right delimiter ("}}") is preceded by a space and minus sign (" -}}"), all leading white space is trimmed from the immediately following text.

This may remove the need for trimming spaces in the renderer functions (eg: https://github.com/bytesparadise/libasciidoc/blob/master/pkg/renderer/html5/section.go#L122)

**Comment by gdamore** [comment]
Yes that would be nice.  I had noticed this myself.

**Comment by gdamore** [comment]
Note that {{- and -}} remove *external* space, not the space in side the rendered object. 
I think one of the purposes of this is to allow templates to span multiple lines for readability, while having the output elide the newlines (eliminating unintentional intervening whitespace).

Probably what we should do use rules in the grammar to include whitespace (consume it from the input) at the right places, but not include it in the parsed element.  But only if that's appropriate.  It's not clear to me in many cases that it *is* appropriate to do that.

**Comment by xcoulon** [comment]
> Note that {{- and -}} remove _external_ space, not the space in side the rendered object.
> I think one of the purposes of this is to allow templates to span multiple lines for readability, while having the output elide the newlines (eliminating unintentional intervening whitespace).
> 
yes, that's also what I realized very recently. I guess I opened this issue as a reminder to explore this syntax, without much investigation at that time.

> Probably what we should do use rules in the grammar to include whitespace (consume it from the input) at the right places, but not include it in the parsed element. But only if that's appropriate. It's not clear to me in many cases that it _is_ appropriate to do that.

Yes, I've started using the `strings.Trim` func to remove heading and trailing spaces in some cases. And I agree with you that maybe the parser should include more spaces in some cases.

**Comment by gdamore** [comment]
I recommend closing this.  The new templates don't really need this, and we can *and should* fix this in the parser, if its appropriate.  (There are a few cases where it is.)

**Comment by xcoulon** [comment]
sounds good to me. The vast refactoring you did recently makes this issue obsolete indeed! 🙌
