### ISSUE TITLE
Support 'leveloffset' as a document attribute

### ISSUE THREAD

**Issue by xcoulon** [bytesparadise/libasciidoc#313]
Eg:
```
:leveloffset: +1

include::chapter-a.adoc[]

include::chapter-b.adoc[]

:leveloffset: -1
```

**Comment by gdamore** [comment]
This would be cool.  I actually use this in some contexts (in an enclosing book document -- although right now I'm only using that when generating PDF, so my priority here is lower -- at least until this project grows PDF support.  😛

**Comment by xcoulon** [comment]
done in #883 (or earlier)
