### ISSUE TITLE
SinglePlusPassThrough with spaces conflicts with LineBreak.

### ISSUE THREAD

**Issue by odknt** [bytesparadise/libasciidoc#337]
I think the below test should be failed.

https://github.com/bytesparadise/libasciidoc/blob/00c01325949fe154014a4c91ce78702ffd04710b/pkg/parser/passthrough_test.go#L170-L188

If allow contain spaces between plus and contents, parser cannot tell the difference between `SinglePlusPassThrough` and `LineBreak`. 

`asciidoctor` parsed `+ *hello*, world +` as follows:

```
<p>+ <strong>hello</strong>, world<br></p>
```

**Comment by xcoulon** [comment]
thanks for opening this issue @odknt I'll take a look at it

**Comment by xcoulon** [comment]
@odknt sorry for the late fix, I was deep into another issue. Please let me know if the fix is OK for you, and feel free to open new issues if you find other bugs ;)

**Comment by odknt** [comment]
@xcoulon thanks for fixing. :smile:
