### ISSUE TITLE
Invalid generated HTML when listing block contains HTML tags

### ISSUE THREAD

**Issue by shuLhan** [bytesparadise/libasciidoc#341]
*Update:* This issue turn out broader than initial issue titled "Double less-than sign '<<' not displayed correctly on listing block", and that is why there are two cases (to keep history of initial report)

## Environment

libasciidoc version 0.2.0.

The expected output is generated using asciidoctor CLI.

## First case

Input in asciidoc format,

```
----
 a<<b
----
```

Expected output in generated HTML,

```
<pre>a&lt;&lt;b</pre>
```

Actual output in generated HTML,

```
<pre>a&lt;<b< pre="">
</b<></pre>
```

## Second case

Input in asciidoc format,
```
----
<a>link</a>
----
```

Expected output in generated HTML format,

```
<div class="listingblock">
<div class="content">
<pre>&lt;a&gt;link&lt;/a&gt;</pre>
</div>
</div>
```

Actual output in generated HTML format,

```
<div class="listingblock">
<div class="content">
<pre><a>link</a></pre>
</div>
<div class="listingblock">
```

**Comment by xcoulon** [comment]
thanks for reporting this issue @shuLhan! I'll look into that

**Comment by xcoulon** [comment]
@shuLhan sorry for the delay in fixing this bug. Please let me know if it works for you now. Also, feel free to report other bugs if you find any ;)
