### ISSUE TITLE
Can libasciidoc "Walk" over parsed AsciiDoc document?

### ISSUE THREAD

**Issue by PicoSushi** [bytesparadise/libasciidoc#342]
I'm looking for AsciiDoc parser which has traversing over parsed document, like [filepath.Walk](https://golang.org/pkg/path/filepath/#Walk) .

Does libasciidoc have such function, or any plan for supporting it?

FYI: Blackfriday, a markdown parser has walk function.
[russross/blackfriday: Blackfriday: a markdown processor for Go](https://github.com/russross/blackfriday)

**Comment by xcoulon** [comment]
hello @PicoSushi 
There's the [`Visitable`](https://github.com/bytesparadise/libasciidoc/blob/master/pkg/types/grammar_types.go#L23-L25) interface that some types implement, so you can [parse](https://github.com/bytesparadise/libasciidoc/blob/master/pkg/parser/asciidoc_parser_test.go#L18) the document and "walk" through it. Is it what you're looking for?

**Comment by PicoSushi** [comment]
Thanks for answer, but my question was incorrect for my purpose.

I'd like to create own renderer, like emoji conversion (`:+1:` to :+1:) in HTML renderer or convert asciidoc to LaTeX, Markdown, etc. So, my question should not be about "Walk"ing, but about making own renderer.

And, there's html5 renderer's [source code](https://github.com/bytesparadise/libasciidoc/tree/736a89df19689cc86bb4f0acd9c9265e3bc787c2/pkg/renderer/html5), so I can use this as implementation example.

Thanks for useful and clean library and quick response!

**Comment by xcoulon** [comment]
@PicoSushi ok, I see. There were 2 parts in your answer above:

> I'd like to create own renderer, like emoji conversion (`:+1`: to 👍) in HTML renderer

There is no support for emojis yet, but that's something I would like to have in the future. In the mean time, we should have support for custom macros soon (see https://github.com/bytesparadise/libasciidoc/pull/347) so you could register your own extension for emojis, until we have a built-in `emoji:` inline macro.

> convert asciidoc to LaTeX, Markdown, etc.

yes, for that, you should probably use the result of the `parser.ParseDocument(...)` function and do something similar to what was done in the HTML renderer.

Hope this helps.
