### ISSUE TITLE
Backtick (monospace text format) issue with other text formatting

### ISSUE THREAD

**Issue by shuLhan** [bytesparadise/libasciidoc#354]
## Raw Input

```
`*a`

`_a_`

`a_b`

`a_b_`

`a*b`

`a*b*`

`a~b~`

`a
b`

`a link:/[b]`
```

## Expected HTML output

Using asciidoctor v2.0.9,  (the "paragraph" wrapper are removed for clarity),

```
<p><code>*a</code></p>

<p><code><em>a</em></code></p>

<p><code>a_b</code></p>

<p><code>a_b_</code></p>

<p><code>a*b</code></p>

<p><code>a*b*</code></p>

<p><code>a<sub>b</sub></code></p>

<p><code>a
b</code></p>

<p><code>a <a href="/">b</a></code></p>
```

## Actual HTML output

Using libasciidoc 736a89df1968, (the "paragraph" wrapper are removed for clarity),

```
<p>`*a`</p>

<p><code><em>a</em></code></p>

<p>`a_b`</p>

<p>`a<em>b</em>`</p>

<p>`a*b`</p>

<p>`a<strong>b</strong>`</p>

<p>`a<sub>b</sub>`</p>

<p>`a
b`</p>

<p><code>a link:/[b]</code></p>
```

**Comment by xcoulon** [comment]
Thanks for such a comprehensive report, @shuLhan! 👍
I'll take a look at it

**Comment by xcoulon** [comment]
with https://github.com/bytesparadise/libasciidoc/pull/357, output is now: 
```
<div class="paragraph">
<p><code>*a</code></p>
</div>

<div class="paragraph">
<p><code><em>a</em></code></p>
</div>

<div class="paragraph">
<p><code>a_b</code></p>
</div>

<div class="paragraph">
<p><code>a_b_</code></p>
</div>

<div class="paragraph">
<p><code>a*b</code></p>
</div>

<div class="paragraph">
<p><code>a*b*</code></p>
</div>

<div class="paragraph">
<p><code>a<sub>b</sub></code></p>
</div>

<div class="paragraph">
<p><code>a
b</code></p>
</div>

<div class="paragraph">
<p><code>a <a href="/">b</a></code></p>
</div>
```

**Comment by shuLhan** [comment]
@xcoulon FYI, I think there is an infinite loop after the commit 21f6c7f8cf662fbb93d114c446f7431c949edff1.
I will try to my best to debug it and may report it again later.

**Comment by xcoulon** [comment]
@shuLhan would you have an example of Asciidoc file to reproduce, please?

**Comment by shuLhan** [comment]
@xcoulon  here is the example of file https://github.com/golang-id/web/blob/master/content/doc/faq/index.adoc

**Comment by xcoulon** [comment]
> @xcoulon here is the example of file https://github.com/golang-id/web/blob/master/content/doc/faq/index.adoc

ok, then don't worry, my next PR will fix that problem. I'll merge it soon.

**Comment by xcoulon** [comment]
@shuLhan could you give it a try again with the latest changes (https://github.com/bytesparadise/libasciidoc/pull/360), please?

**Comment by shuLhan** [comment]
OK.  I will try it later.  Thanks.
