### ISSUE TITLE
Evaluate performance

### ISSUE THREAD

**Issue by xcoulon** [bytesparadise/libasciidoc#361]
Libasciidoc becomes significantly slow on large documents (eg: https://github.com/golang-id/web/blob/master/content/doc/faq/index.adoc).

Let's see if there are ways to optimize the parsing since this is where most of the time is spent (rendering is quite fast, comparatively)

**Comment by odknt** [comment]
I tried fix libasciidoc for reduce evaluation time, but I noticed that need fix pigeon before libasciidoc.
The code generated by pigeon is slow.

Libasciidoc parsed the below code took about `2.4s` on my machine.  
https://github.com/golang-id/web/blob/master/content/doc/faq/index.adoc

**pigeon**

* Use `+` instead of `fmt.Sprintf` (`0.6s` reduced)
    `fmt.Sprintf` is very slow.
* Refactor `state` from map to slice (`0.5s` reduced)
    `cloneState()` is slow that copying all `map` entries.

**libasciidoc**

* Enable `-optimize-parser` option when `make generate-optimize` (`0.6s` reduced)
    Debug related codes have been deleted (ex. `parser.Debug` `parser.Statistics`)
* Small fix that `state` related codes.

I measured parse and render time before apply above changes and after. The result is following.

```
$ time ./libasciidoc-e0ac68b test.adoc
    0m02.43s real     0m02.68s user     0m00.02s system

$ time ./libasciidoc-optimized test.adoc
    0m00.72s real     0m00.79s user     0m00.02s system
```

There is still room for improvement on pigeon (ex. refactor `parseExpr` from recursion to loop and goto)

**Comment by xcoulon** [comment]
awesome! thanks for your feedback, @odknt ! 
I'm currently refactoring the grammar but it's still going to take a bit of time before I can commit it, but the hints that you pointed are definitely interesting, too!

Could you elaborate on the "Small fix that `state` related codes.", please?

**Comment by odknt** [comment]
We need fix related codes to compilable by using the refactored `state` in pigeon.

But I guess `state` refactoring is not good for many pigeon users, because map implemented `state` is slower than  slice only when map's entries not many (about less than 100 entries)

**Comment by xcoulon** [comment]
> We need fix related codes to compilable by using the refactored `state` in pigeon.
> 
> But I guess `state` refactoring is not good for many pigeon users, because map implemented `state` is slower than slice only when map's entries not many (about less than 100 entries)

I need to dig a little deeper into this, but I guess that such a `state` refactoring could be an interesting improvement for pigeon, even if small documents don't benefit from it. Hence, that could be a good candidate PR.

**Comment by xcoulon** [comment]
@odknt I've opened https://github.com/mna/pigeon/pull/86 to remove 3 uses of `fmt.Sprintf` in the generated parser. 
Also, when combined with the WIP that I pushed on https://github.com/xcoulon/libasciidoc/tree/Issue362_refactor_grammar (grammar needs to be `generated-optimized`, then the parsing of a large document of 65kb goes from 
```
$ time libasciidoc -s  ./tmp/large.adoc
libasciidoc -s ./tmp/large.adoc  0.80s user 0.05s system 124% cpu 0.684 total
```
to 
```
$ time libasciidoc -s  ./tmp/large.adoc
libasciidoc -s ./tmp/large.adoc  0.17s user 0.04s system 122% cpu 0.172 total
```
This WIP is a large refactoring of the grammar along with some of your suggestions above ;) The amount of changes explain the time it took me to get through all of it ;)

**Comment by odknt** [comment]
@xcoulon Awesome! I've been so busy I totally forgot that.
The PR makes me happy. However, I think should be change `builder/static_code.go` instead of `builder/generated_static_code.go`.
If my memory serves, `generated_static_code.go` is generate from `static_code.go`.

**Comment by xcoulon** [comment]
> @xcoulon Awesome! I've been so busy I totally forgot that.
> The PR makes me happy. However, I think should be change `builder/static_code.go` instead of `builder/generated_static_code.go`.
> If my memory serves, `generated_static_code.go` is generate from `static_code.go`.

ok, thanks for the feedback @odknt, I'll check that. 

Also, when looking at the generated libasciidoc parser when using the `optimize-parser` flag, I could not finf any reference to the `state` as you mentioned in https://github.com/bytesparadise/libasciidoc/issues/361#issuecomment-497998875. So I guess there's nothing to do about it if we keep using the `optimize-parser` flag from now on...

**Comment by odknt** [comment]
> Also, when looking at the generated libasciidoc parser when using the optimize-parser flag, I could not finf any reference to the state as you mentioned in #361 (comment). So I guess there's nothing to do about it if we keep using the optimize-parser flag from now on...

I think so too.

**Comment by xcoulon** [comment]
Added some bench in https://github.com/bytesparadise/libasciidoc/pull/369

**Comment by pgorod** [comment]
This is probably a bit off-topic here, but I just want a way to get in touch with the wonderful people driving this project and say "thank you" 🎉 . 

I work on an 100% free and open-source CRM called SuiteCRM and we made our new Documentation site based on Hugo and Asciidoc. We're currently using the extremely slow Ruby asciidoc parser (95 seconds for a full build...).

Source https://github.com/salesagility/SuiteDocs/
Site https://docs.suitecrm.com

I just wanted to say I'm eager to see this project here going into Hugo and drastically improving our build times. Please feel free to use our project for tests, benchmarks etc if you think it's useful. And tell me if there's something I can do for you. Thanks!

**Comment by xcoulon** [comment]
> This is probably a bit off-topic here, but I just want a way to get in touch with the wonderful people driving this project and say "thank you" 🎉 .
> 
> I work on an 100% free and open-source CRM called SuiteCRM and we made our new Documentation site based on Hugo and Asciidoc. We're currently using the extremely slow Ruby asciidoc parser (95 seconds for a full build...).
> 
> Source https://github.com/salesagility/SuiteDocs/
> Site https://docs.suitecrm.com
> 
> I just wanted to say I'm eager to see this project here going into Hugo and drastically improving our build times. Please feel free to use our project for tests, benchmarks etc if you think it's useful. And tell me if there's something I can do for you. Thanks!

Thanks for your feedback @pgorod, I truly appreciate 😊
You could help by trying the current build (you can build and install locally with `make install`) on your docs and report bugs, missing features or speed benchmarks, for example.

**Comment by pgorod** [comment]
Sure, I'll give it a try. Do I have to do anything to get Hugo to use your software instead of the Ruby one? How do I "redirect" Hugo to the new engine?

**Comment by xcoulon** [comment]
Also, compare benchmarks with optimized grammar vs "standard" grammar with `memoize` enabled.

**Comment by xcoulon** [comment]
> Sure, I'll give it a try. Do I have to do anything to get Hugo to use your software instead of the Ruby one? How do I "redirect" Hugo to the new engine?

Sorry for the late response, @pgorod. I tried to integrate Hugo with libasciidoc a long time ago but  the latter was not ready for release at the time. I'll check again the code and see if I can provide you with a fork. I'll also need to see what metadata are worth returning to Hugo to integrate nicely (title, author, table of contents, etc.)

**Comment by xcoulon** [comment]
Comparing `optimized-parser` vs `optimized-grammar` options, the former is much faster than the latter, even with the `memoize` option enabled:
```
name                 old time/op    new time/op    delta
Parser/1_line-8        49.3µs ± 0%    64.9µs ± 1%  +31.58%  (p=0.000 n=7+10)
Parser/10_lines-8       574µs ± 1%     888µs ± 1%  +54.62%  (p=0.000 n=9+9)
Parser/vert.x_doc-8    59.4ms ± 0%   106.0ms ± 2%  +78.46%  (p=0.000 n=8+10)

name                 old alloc/op   new alloc/op   delta
Parser/1_line-8        28.1kB ± 0%    24.7kB ± 0%  -11.97%  (p=0.000 n=10+10)
Parser/10_lines-8       216kB ± 0%     253kB ± 0%  +17.23%  (p=0.000 n=10+10)
Parser/vert.x_doc-8    19.0MB ± 0%    25.0MB ± 0%  +31.54%  (p=0.000 n=10+10)

name                 old allocs/op  new allocs/op  delta
Parser/1_line-8           417 ± 0%       539 ± 0%  +29.26%  (p=0.000 n=10+10)
Parser/10_lines-8       6.41k ± 0%     7.21k ± 0%  +12.45%  (p=0.000 n=10+10)
Parser/vert.x_doc-8      690k ± 0%      933k ± 0%  +35.14%  (p=0.000 n=10+10)
```

Comparing commit (latest on `master` at the time of writing) vs 335906b, we have the following improvements (a combination of mna/pigeon improvements and local changes in the grammar):
```
name                 old time/op    new time/op    delta
Parser/1_line-8        84.3µs ± 1%    49.3µs ± 0%  -41.54%  (p=0.000 n=9+7)
Parser/10_lines-8       881µs ± 1%     574µs ± 1%  -34.85%  (p=0.000 n=9+9)
Parser/vert.x_doc-8    66.9ms ± 1%    59.4ms ± 0%  -11.25%  (p=0.000 n=9+8)

name                 old alloc/op   new alloc/op   delta
Parser/1_line-8        38.4kB ± 0%    28.1kB ± 0%  -26.83%  (p=0.000 n=10+10)
Parser/10_lines-8       306kB ± 0%     216kB ± 0%  -29.43%  (p=0.000 n=10+10)
Parser/vert.x_doc-8    20.5MB ± 0%    19.0MB ± 0%   -7.32%  (p=0.000 n=10+10)

name                 old allocs/op  new allocs/op  delta
Parser/1_line-8           701 ± 0%       417 ± 0%  -40.51%  (p=0.000 n=10+10)
Parser/10_lines-8       9.10k ± 0%     6.41k ± 0%  -29.54%  (p=0.000 n=10+10)
Parser/vert.x_doc-8      795k ± 0%      690k ± 0%  -13.14%  (p=0.000 n=9+10)
```

**Comment by xcoulon** [comment]
Closing this issue after this round of improvements.

**Comment by pgorod** [comment]
@xcoulon I would like to invite you to participate in this thread I started on the Hugo forums about `libasciidoctor`.

https://discourse.gohugo.io/t/libasciidoc-a-golang-asciidoc-renderer/21702

**Comment by xcoulon** [comment]
> @xcoulon I would like to invite you to participate in this thread I started on the Hugo forums about `libasciidoctor`.
> 
> https://discourse.gohugo.io/t/libasciidoc-a-golang-asciidoc-renderer/21702

thanks for starting this thread and inviting me to contribute, @pgorod! I've started responding, so let's keep the conversation going and see what we can do :)
