### ISSUE TITLE
Get list of headings

### ISSUE THREAD

**Issue by Arteneko** [bytesparadise/libasciidoc#363]
Is there a way to get the list of headings from the document?

The goal would be to access a list of found headings (`=` to `====` for example),
to be able to implement a custom outline.

**Comment by xcoulon** [comment]
hello @IvanDelsinne 
yes, that would be doable: we should be able to return that in the call to `libasciidoc.ConvertFileToHTML`. May I ask if you're planning to build an IDE extension with libasciidoc?

**Comment by IvanDelsinne** [comment]
Instead of an IDE extension, I'm planning to build a little adoc-based wiki.

**Comment by IvanDelsinne** [comment]
I think it may be better, instead of simply returning the outline as result, to return a struct with every "metadata" that can be gained about the document.

**Comment by xcoulon** [comment]
> I think it may be better, instead of simply returning the outline as result, to return a struct with every "metadata" that can be gained about the document.

yes, and that's the plan, actually. For now, you can retrieve the document's title, but we could add more data, such as the outline, authors, etc.

**Comment by xcoulon** [comment]
@IvanDelsinne before I start working on this: what kind of format would you prefer ? I could return a "flat list" of elements that describe the section
```
type Section struct {
  Level int    // 0-5
  Title string // just plain text instead of hyperlink, quoted text, etc.
}
```
or something more hierarchical:
```
type Section struct {
  Level int    // 0-5
  Title string // just plain text instead of hyperlink, quoted text, etc.
  Children []Section
}
```

do you have any preference?

**Comment by xcoulon** [comment]
Long overdue but here's finally a PR to address your request @Arteneko: https://github.com/bytesparadise/libasciidoc/pull/485
Also, please note that the table of contents returned in the new `types.Metadata` object is in a hierarchical mode, since this is also the kind of content that Hugo expects (and I'm going to work on the integration soon)

(btw, did you change your GH handle?)

**Comment by Arteneko** [comment]
I kind of left out this issue, among many, because of work and such, so it digs out an old topic.

Fine by me, a flattening method is pretty trivial to implement to obtain a flat list of headings, and if the hierarchy is a useful info to keep, that makes sense.

(I did)

**Comment by xcoulon** [comment]
ok, thanks for your feedback @Arteneko and again, sorry for the delay.
