### ISSUE TITLE
Comma inside link's description clear the rest of characters

### ISSUE THREAD

**Issue by shuLhan** [bytesparadise/libasciidoc#388]
Hi @xcoulon ,

I would like to report some issue again with text inside `link` description.  This is tested on master branch on commit 5321fe2e765e.

== Environments

libasciidoc v0.2.1-0.20190826055451-5321fe2e765e

== Input

```
link:/[A, B, and C]
```

== Actual Output

```
<a href="/">A</a>
```

==  Expected Output

```
<a href="/">A, B, and C</a>
```

I am sorry, I can't help with code, only reporting issues  :/

**Comment by xcoulon** [comment]
@shuLhan thanks for reporting this issue, I'll look into it. 

> I am sorry, I can't help with code, only reporting issues :/

reporting is already helping ;)

**Comment by xcoulon** [comment]
@shuLhan this should be fixed in `master`. Please let me know if it works for you now
