### ISSUE TITLE
Some "link" macro does not work as expected

### ISSUE THREAD

**Issue by shuLhan** [bytesparadise/libasciidoc#416]
If I am not mistaken, this bug arise since v0.2.0.
== Environment

* libasciidoc v0.2.1-0.20190904185117-3445b3d62993
* libasciidoc v0.2.1-0.20190916201756-cc4c79db3832

== Test case

```
Test 1
link:/does/not/#work[as expected]
Test 2
link:/also/does/not/work.pdf[as expected]
```

== Expected output

```
Test 1
<a href="/does/not/#work">as expected</a>
Test 2
<a href="/also/does/not/work.pdf">as expected</a>
```

==  Actual output

```
Test 1
link:/does/not/#work[as expected]
Test 2
link:/also/does/not/work.pdf[as expected]
```

**Comment by xcoulon** [comment]
thanks for reporting this bug, @shuLhan 
I'll take a look at it

**Comment by xcoulon** [comment]
@shuLhan with the code in https://github.com/bytesparadise/libasciidoc/pull/417, I get the following output after installing and executing against the same source as you used:
```
<div class="paragraph">
<p>Test 1
<a href="/does/not/#work">as expected</a>
Test 2
<a href="/also/does/not/work.pdf">as expected</a></p>
</div>
```
