### ISSUE TITLE
The "link" macro does not work if its encoded spaces

### ISSUE THREAD

**Issue by shuLhan** [bytesparadise/libasciidoc#419]
I found another use cases where "link" macro does not works as expected.

==  Environment

Libasciidoc v0.2.1-0.20190919183106-98a84d49adb4

==  Test cases

```
Test 1: link:/test/a b[with space].
Test 2: link:/test/a%20b[with encoded space].
```

==  Expected output

Tested with asciidoctor v2.0.10

```
<p>Test 1: link:/a b[with space].
Test 2: <a href="/a%20b">with encoded space</a>.</p>
```

==  Actual output

```
<p>link:/a b[with space].
link:/a%20b[with encoded space].</p>
```

**Comment by xcoulon** [comment]
thanks for reporting this issue @shuLhan
I'll take care of it

**Comment by xcoulon** [comment]
it should be fixed now, @shuLhan 
for some reason, I removed `%` from the list of valid characters in an URL :/
