### ISSUE TITLE
prefix generated section ids with '_'

### ISSUE THREAD

**Issue by xcoulon** [bytesparadise/libasciidoc#446]
To comply with asciidoc/asciidoctor

**Comment by gdamore** [comment]
Turns out I want this too, as my CSS depends on it.

**Comment by xcoulon** [comment]
ok, let me add it to this milestone so we can finally address it ;)

**Comment by xcoulon** [comment]
@gdamore I just tested and I believe this is already done. Could you let me know if there's any gap that still needs to be filled?

eg:
```
= title 1

== title 2

=== title 3

==== title 4

```
renders as:
```
...
<div id="header">
<h1>title 1</h1>
</div>
<div id="content">
<div class="sect1">
<h2 id="_title_2">title 2</h2>
<div class="sectionbody">
<div class="sect2">
<h3 id="_title_3">title 3</h3>
<div class="sect3">
<h4 id="_title_4">title 4</h4>
</div>
</div>
</div>
</div>
</div>
...
```

**Comment by gdamore** [comment]
I think I saw the same yesterday so I wanted to test a bit more before I commented further.  I think you should just close the issue.

**Comment by xcoulon** [comment]
ok, thanks for confirming @gdamore 👍 
Please don't hesitate to reopen this issue if you find something wrong!
