### ISSUE TITLE
Use GitHub actions to build the PR

### ISSUE THREAD

**Issue by xcoulon** [bytesparadise/libasciidoc#448]
If Actions support building on Linux + macOS + Windows, then this could be a candidate to replace Travis-CI and Appveyor.

**Comment by moorereason** [comment]
You're already doing Windows builds in Travis-CI, so you should be able to kill the Appveyor integration.

As for GH Actions, you may want to wait for the dust to settle around https://github.com/actions/setup-go/issues/12 to avoid a lot of hoop jumping for the `install-devtools` make target.

Useful tips in this repo: https://github.com/mvdan/github-actions-golang

You could probably integrate the [codecov](https://github.com/marketplace/actions/codecov) and [golangci-lint](https://github.com/marketplace/actions/golangci-lint-action) actions in the process.

**Comment by xcoulon** [comment]
thanks for the links, @moorereason!
Right, I could probably get rid of the AppVeyor integration now. I had kept it in parallel while adding the support for Windows on Travis-CI, and since it's been reliable, I guess I can do soon
