### ISSUE TITLE
Support for xref cross links

### ISSUE THREAD

**Issue by gdamore** [bytesparadise/libasciidoc#459]
I'm using a lot of xref: markup, and libasciidoc doesn't grok it.

E.g.:

```
xref:nng_listener_setopt.3.adoc[nng_listener_setopt(3)],
```

which should render on the output as

```
<a href="nng_listener_setopt.3.html">nng_listener_setopt(3)</a>,
```

But is not rendered at all by libasciidoc (well is rendered by passing straight through without transformation).

**Comment by xcoulon** [comment]
thanks for reporting this issue @gdamore, I will look into it
