### ISSUE TITLE
Date on last-update footer differs

### ISSUE THREAD

**Issue by gdamore** [bytesparadise/libasciidoc#461]
Comparing to asciidoctor itself, it appears that libasciidoc uses the date the program was run, rather than looking at the last modification date (mtime) of the file being converted.  For example, I just ran two conversions on a file I updated over a week ago -- one using asciidoctor and the other using libasciidoc:

The footer diff looks like this:

```
 <div id="footer">
 <div id="footer-text">
-Last updated 2020/01/02 09:48:23 PST
+Last updated 2019-12-22 02:51:27 -0800
 </div>
 </div>
 </body>
```

Here's the source file:

```
-rwxrwxrwx 1 garrett garrett 4283 Dec 22 02:51 nng_setopt.3.adoc
```

(I also notice the difference that timezone renders differently, but its entirely possible that this is due to the fact that I did the libasciidoc rendering on a Windows box, but the asciidoctor render was done on Ubuntu (actually WSL on the same host) -- the two platforms may have different ideas about how to represent the timezone.)

**Comment by xcoulon** [comment]
ah good point, thanks for pointing this error, @gdamore. I'll use the last modification time of the file, instead
