### ISSUE TITLE
Remove build with AppVeyor

### ISSUE THREAD

**Issue by xcoulon** [bytesparadise/libasciidoc#478]
Travis has been supporting builds on Windows and it's been reliable, so no need to request the same builds on another platform.

**Comment by gdamore** [comment]
GitHub Actions has been my CI/CD of choice recently -- easier than Circle, more reliable than pretty much any of the others, and faster across the board.

**Comment by xcoulon** [comment]
closing as done: now using GitHub actions to build and test on Linux, macOS and Windows.
