### ISSUE TITLE
// comment does not function properly if right after title

### ISSUE THREAD

**Issue by gdamore** [bytesparadise/libasciidoc#481]
This is a difference in handling vs. asciidoctor

If I have 

= Title
// Copyright blah blah blah
// more boilerplate

Then the // is taken as an author.  If I insert a new line in front of the boilerplate, it's fine.

The main concern here is that this behavior differs from asciidoctor.  I have a large body of documents that lacks that extra whitespace.

**Comment by xcoulon** [comment]
ok, thanks for reporting this issue @gdamore and you're right, the goal is to be as compatible with Asciidoctor as possible, so I will address that

**Comment by xcoulon** [comment]
@gdamore please let me know if the PR addressed your concern, otherwise feel free to reopen this issue ;)
