### ISSUE TITLE
would be nice to have the ability to link to stylesheet

### ISSUE THREAD

**Issue by gdamore** [bytesparadise/libasciidoc#482]
The generated document doesn't include any style sheet data at all.  But my asciidoctor generated files do -- they either embed a whole style sheet, or link to it via ./asciidoctor.css -- they also in my case link to google font servers to pick up OpenSans.

Probably you don't want to include the stock style sheet, but it would be nice if we could specify either style sheet, or more "link" attributes to include in the meta section.

I can of course post-process the document and inject those myself, but it seems kind of dirty to do that.

**Comment by xcoulon** [comment]
sure, that's what I had in mind with https://github.com/bytesparadise/libasciidoc/issues/63, actually ;) I'll address that gap.

**Comment by xcoulon** [comment]
Actually, I will keep #63 open to embed a CSS in the generated HTML documents, but in the mean time I can add a `--css` argument to the CLI so the HTML documents have a `<link type="text/css" rel="stylesheet" href="<value>">` their the `<head>` section. Would that work for you @gdamore?

**Comment by gdamore** [comment]
Yes that would do the trick for me.

**Comment by xcoulon** [comment]
@gdamore please let me know if the PR addressed your issue, otherwise feel free to open it again ;)

**Comment by gdamore** [comment]
I haven't tested it, but casual inspection makes me think it will do so.

We're so close to having all the things I want from this package -- and then I can start throwing away the mess of shell scripts I have to preprocess docs, and post process output, and replace them with some very nice Go code that wraps around libasciidoc.

I think the only really significant thing remaining from my part is support for syntax highlighting.  (I'd love a pygments compatible one, but I'm happy to see any one that I can style accordingly.)

**Comment by xcoulon** [comment]
> I haven't tested it, but casual inspection makes me think it will do so.
> 
> We're so close to having all the things I want from this package -- and then I can start throwing away the mess of shell scripts I have to preprocess docs, and post process output, and replace them with some very nice Go code that wraps around libasciidoc.
> 
> I think the only really significant thing remaining from my part is support for syntax highlighting. (I'd love a pygments compatible one, but I'm happy to see any one that I can style accordingly.)

Thanks for your feedback @gdamore! 
I'll address your request about syntax highlighting (#488) before #484 then.
