### ISSUE TITLE
document attributes from the command line?

### ISSUE THREAD

**Issue by gdamore** [bytesparadise/libasciidoc#484]
I sometimes want to supply different attributes on the same document, depending on whether I'm rendering for print or for online use.  Therefore it's somewhat inconvenient to require that attributes only appear inline.

With the command line tool, I'd like to be able to e.g. supply "-aicons=font" to enable font icons.

**Comment by xcoulon** [comment]
thanks opening this issue @gdamore, I will work on it.

**Comment by gdamore** [comment]
I can probably put together a PR that at least provides an option for this so that it can be used with ConvertToHTML.  This would allow me to use it in my own Go code, which would get about 95% of the way to what I need.  But if you're already working on it, I'll wait.

**Comment by xcoulon** [comment]
thanks for the proposal but yes I've started working on it, but I'm not fully done yet. Hopefully soon ;)

**Comment by xcoulon** [comment]
@gdamore it should work now, including the `-a!foo` syntax to unset the `foo` attribute in the document. Could you give it a try and let me know if it works for you, please?

Note that the API changed (in case you also embed the library in one of your Go projects): https://github.com/bytesparadise/libasciidoc/pull/495/files#diff-4f72c4c2b08ab8542e4a8babeb3ac735

**Comment by gdamore** [comment]
Thanks I will give it a shot.
