### ISSUE TITLE
syntax highlight support

### ISSUE THREAD

**Issue by gdamore** [bytesparadise/libasciidoc#488]
One of the nice features in asciidoctor is rich support for syntax highlighting via pygments.

I seems like it would nice to offer something similar -- and indeed a pygments compatible parser in pure Go seems to exist already : https://github.com/alecthomas/chroma   -- it's even MIT licensed.

Maybe we could run the source code blocks through this to get pygments stylesheet compatible markup?

I think we're very close to closing all of my "shortcomings" keeping me from adopting this in my project and ditching asciidoctor and it's heavy weight tool chain.

At some point I'd like to contribute additional things to this project (like better support for semantic markup, better support for customization of the output, and maybe even additional backends -- for example it should not be hard to emit EPUB with only modest changes to the current HTML5 backend (mostly we need to use semantic markup I think).  These might be things that are shortcomings in asciidoctor itself -- it's too hard to work meaningfully in ruby (for me) though.

**Comment by gdamore** [comment]
Thanks for all your work on -- just to let you know I'm anxiously awaiting this so that I can switch my workflow from asciidoctor. :-)

**Comment by xcoulon** [comment]
@gdamore please give a try to the latest changes and let me know if they fill your requirements ;) (or feel free to open another issue to let me know if there's still something missing!)

**Comment by gdamore** [comment]
I just saw this -- was out of town -- will definitely give it a whirl!  Woot!!

**Comment by gdamore** [comment]
Seems to work!

It's kind of a pain for me to make use of right now because I don't have inline document attributes -- this is something I enable differently based on what the file format is.  (In retrospect, maybe I could have made this one unconditional, but generally I don't have lots of document attributes instead my current tree relies on setting them on the command line.)

**Comment by xcoulon** [comment]
> Seems to work!
> 
> It's kind of a pain for me to make use of right now because I don't have inline document attributes -- this is something I enable differently based on what the file format is. (In retrospect, maybe I could have made this one unconditional, but generally I don't have lots of document attributes instead my current tree relies on setting them on the command line.)

by "inline document attributes", did you mean https://github.com/bytesparadise/libasciidoc/issues/484 ?
