### ISSUE TITLE
parser fails on when display parameters followed by extra blank line

### ISSUE THREAD

**Issue by gdamore** [bytesparadise/libasciidoc#493]
(Arguably this was an error in the source document, but asciidoctor didn't trip over it.)

I had a document where I had a display like this:

```
[.text-left]

xref:nng_tls_config_alloc.3tls.adoc[nng_tls_config_alloc(3tls)],
xref:nng_tls_config_auth_mode.3tls.adoc[nng_tls_config_auth_mode(3tls)],
xref:nng_tls_config_ca_chain.3tls.adoc[nng_tls_config_ca_chain(3tls)],
xref:nng_tls_config_own_cert.3tls.adoc[nng_tls_config_own_cert(3tls)],
xref:nng_tls_config_free.3tls.adoc[nng_tls_config_free(3tls)],
xref:nng_tls_config_hold.3tls.adoc[nng_tls_config_hold(3tls)],
xref:nng_tls_config_server_name.3tls.adoc[nng_tls_config_server_name(3tls)],
xref:nng.7.adoc[nng(7)]
```

When I tried to process with using libasciidoc, the parser fell over on it.

asciidoctor did handle this, and seemed to generate reasonable output. 

I've fixed my source document, but I wanted to record this as as it represents a change in behavior.

**Comment by xcoulon** [comment]
ok, I will take a look at this bug. Thanks for reporting it!
