### ISSUE TITLE
parser error from Concealed Index term

### ISSUE THREAD

**Issue by gdamore** [bytesparadise/libasciidoc#502]
```
PS C:\Users\garre\Work\nng\docs\man> libasciidoc.exe .\nng_sub.7.adoc
Error: unable to render full document: failed to render document elements: error while rendering section: template: section 1:3:41: executing "section 1" at <renderElements $ctx .Elements>: error calling renderElements: error while rendering section: template: other section:2:35: executing "other section" at <renderElements $ctx .Elements>: error calling renderElements: unable to render labeled list: template: labeled list with default layout:4:84: executing "labeled list with default layout" at <renderInlineElements $ctx $item.Term>: error calling renderInlineElements: unable to render line: unsupported type of element: types.ConcealedIndexTerm
Usage:
  libasciidoc [flags] FILE
  libasciidoc [command]
```

The source document is here:

https://github.com/nanomsg/nng/blob/master/docs/man/nng_sub.7.adoc

**Comment by gdamore** [comment]
There are a lot of docs in that directory, and they *all* parse properly with asciidoctor.

I'm trying to automate this with libasciidoc, but ... until I can convert them all, I can't make the switch.

**Comment by gdamore** [comment]
Btw, thanks so much for work on this to this point -- I have high hopes for this project!

**Comment by xcoulon** [comment]
@gdamore ok, thanks for reporting this issue and sorry that you have to face so many bugs 😬 
I will take a look at it.

**Comment by xcoulon** [comment]
@gdamore this should be fixed now. Could you give it a try, please?

**Comment by xcoulon** [comment]
@gdamore I will also work on supporting the `-R` and `-D` arguments as in Asciidoctor, so you can process a whole directory in a single command. See https://github.com/bytesparadise/libasciidoc/issues/508
