### ISSUE TITLE
WithAttributes doesn't seem to do anything

### ISSUE THREAD

**Issue by gdamore** [bytesparadise/libasciidoc#509]
I was trying to use the programmatic API, using configuration.NewConfiguration().WithAttributes(attrs) and the attributes I was setting didn't seem to work.  Preprocessing the document to inject them inline in the document does work:

My attributes are:

	attrs := map[string]string{
		"icons":              "font",
		"source-highlighter": "pygments",
		"doctype":            "manpage",
		"linkcss":            "yes",
		//"mansource":          "NNG",
		//"manmanual":          "NNG Reference Manual",
	}

	config := configuration.NewConfiguration(
		configuration.WithAttributes(attrs),
		configuration.WithHeaderFooter(true),
		configuration.WithFilename(info.Name()))

Passing this config to 

	m, err := libasciidoc.ConvertToHTML(strings.NewReader(pre.String()), out, config)

Didn't work.

The code that *does* work does this instead:

	for scanner.Scan() {
		line := scanner.Text()
		_, _ = fmt.Fprintln(pre, line)

		if page == "" && strings.HasPrefix(line, "= ") {
			page = strings.TrimSpace(line[2:])
			for k, v := range attrs {
				_, _ = fmt.Fprintf(pre, ":%s: %s\n", k, v)
			}
		} else if strings.HasPrefix(line, "== ") {
			chap = strings.TrimSpace(line[3:])
		} else if chap == "NAME" && strings.ContainsRune(line, '-') {
			parts := strings.SplitN(line, "-", 2)
			desc = strings.TrimSpace(parts[1])
		}
	}

Note especially that I'm injecting the inline attributes after the document title.  If I remove that for loop to do this, then it doesn't work.  (Note that some attributes don't work at all, but I can tell that the :icons: font and :source-highlighter: pygments do work as you'd expect when they are inline.

**Comment by xcoulon** [comment]
@gdamore I'm sorry but I can't reproduce the problem, event after adding a couple of tests. See this portion of a PR I just opened: https://github.com/bytesparadise/libasciidoc/pull/513/files#diff-498e7a28a26823a4592ac5009deeb634R251-R262

Also, from the CLI, it works fine. Th example below use a very simple document which is displayed and then processing with a custom attribute passed from the CLI using the `-a` flag: 
```
$ cat tmp/test.adoc
{font}

$ libasciidoc -s -o - -aicons=font tmp/test.adoc
<div class="paragraph">
<p>font</p>
</div>
```

Would you mind sharing an example of code that I can run to reproduce the problem, please?

**Comment by xcoulon** [comment]
> @gdamore I'm sorry but I can't reproduce the problem, event after adding a couple of tests. See this portion of a PR I just opened: https://github.com/bytesparadise/libasciidoc/pull/513/files#diff-498e7a28a26823a4592ac5009deeb634R251-R262
> 
> Also, from the CLI, it works fine. Th example below use a very simple document which is displayed and then processing with a custom attribute passed from the CLI using the `-a` flag:
> 
> ```
> $ cat tmp/test.adoc
> {font}
> 
> $ libasciidoc -s -o - -aicons=font tmp/test.adoc
> <div class="paragraph">
> <p>font</p>
> </div>
> ```
> 
> Would you mind sharing an example of code that I can run to reproduce the problem, please?

ah never mind, I believe I found the problem, and my example above is not what I needed to reproduce it 🤦‍♂

**Comment by xcoulon** [comment]
@gdamore hopefully this is fixed. Could you please confirm that it works for you now?
