### ISSUE TITLE
Would like to be able to configure the Header and Footer separately

### ISSUE THREAD

**Issue by gdamore** [bytesparadise/libasciidoc#510]
I have documents where I generate the header (because I want the section information), but I exclude the footer.  asciidoctor lets me do this.  It seems libasciidoc lacks the ability to configure these.

**Comment by xcoulon** [comment]
@gdamore could you explain how you do this with Asciidoctor? Libasciidoc has the `-s, --no-header-footer` flag, but that for the header and footer at the same time. 
Do you specify a custom HTML template, maybe? Otherwise, how do you do that?

**Comment by gdamore** [comment]
I supply a nofooter attribute.  There is also a noheader attribute that can be set.

**Comment by xcoulon** [comment]
ok, got it! I'll implement that ;)
