### ISSUE TITLE
Can we get a v0.4.0 tag?

### ISSUE THREAD

**Issue by gdamore** [bytesparadise/libasciidoc#512]
This would make it easier to pick up your bug fixes.

**Comment by xcoulon** [comment]
Sure, I can tag with v0.3.1 after I fixed the latest bugs you reported.

**Comment by xcoulon** [comment]
@gdamore I'm taking the liberty to rename this issue to `Can we get a v0.4.0 tag?` because the new milestone also contains new features, not only bug fixes.

**Comment by gdamore** [comment]
Works for me. :-)

**Comment by xcoulon** [comment]
here it is finally, @gdamore! https://github.com/bytesparadise/libasciidoc/releases/tag/v0.4.0
