### ISSUE TITLE
Support the `-b` flag for specific doc type

### ISSUE THREAD

**Issue by xcoulon** [bytesparadise/libasciidoc#527]
so we can have `-b manpage` as an alternative to specifying the doctype in the document itself, with
```
:doctype: manpage
```

**Comment by gdamore** [comment]
(And for the curious, yes, manpage is a possible backend for asciidoctor -- it is distinct from the doctype manpage.  The backend manpage emits TROFF sequences.  The doctype man page affects the rendering of the title section.)

**Comment by xcoulon** [comment]
> Actually -b is for the _backend_, -d is for the doc type.

ah right 🤦‍♂️ 

> I'm fixing the support for -b as part of the fix for #601

I know it's a minor change but it could be addressed in a separate PR (easier to track the change afterwards)

**Comment by gdamore** [comment]
It seems kind of linked -- impossible for anyone to access the XHTML output (short of writing a program to do so) otherwise.

**Comment by xcoulon** [comment]
well, can't you fix this issue here first, and then use it for the XHTML output?

**Comment by gdamore** [comment]
I suppose I could have, but I did the development in the other direction.  I'll submit the unified PR.  If it bothers you greatly, it doesn't look too bad to split apart.

**Comment by gdamore** [comment]
This was fixed with the merge of #618 .
