### ISSUE TITLE
Profiler in CI

### ISSUE THREAD

**Issue by moorereason** [bytesparadise/libasciidoc#580]
Humble comments regarding the recent `bench` make target:

Why run the cpu/mem profiling in CI when you don't have an opportunity to view the resulting files?  It seems like a waste of CI compute time.

Additionally, running benchmarks in CI will not provide truly comparable CPU results (can't trust VM/container CPU resources/priority will be consistent between CI jobs).

My recommendations would be:

1. don't run benchmarking/profling in CI.
1. create a `bench` make target that just runs the benchmarks normally and saves the output to a temp file.  Run the target for each commit you want to compare and then use `benchstat` to compare the results.
1. move the profiling off to a separate make target.

I'm up for submitting a PR for these ideas if you're open to it.

**Comment by xcoulon** [comment]
hello @moorereason 👋 

I agree with you, it doesn't make sense to run the profiling in CI. My only intent here was to make sure that to commands to run would not be broken by a PR.

You're more than welcome to submit a PR with your recommendations!
