### ISSUE TITLE
Misparsed attribute blocks

### ISSUE THREAD

**Issue by gdamore** [bytesparadise/libasciidoc#585]
Admittedly this is probably pushing things, but I have this markup:

```
[.copyright]
icon:staysail[role=copyright1,alt=""]
[.copyright2]*Copyright (C) 2020 mailto:info@staysail.tech["Staysail Systems, Inc"] +
San Marcos, California, United States of America*
```

libasciidoc emits this as:

```
<div class="paragraph copyright">
<p>icon:staysail[role=copyright1,alt=""]
[.copyright2]*Copyright &#169; 2020 <a href="mailto:info@staysail.tech">Staysail Systems, Inc</a><br>
San Marcos, California, United States of America*</p>
</div>
```

But what I'd like it to emit is what asciidoctor does:

```
<div class="paragraph copyright">
<p><span class="icon copyright1"><img src="icons/staysail.svg" alt=""/></span>
<strong class="copyright2">Copyright &#169; 2020 <a href="mailto:info@staysail.tech">Staysail Systems, Inc</a><br/>
San Marcos, California, United States of America</strong></p>
</div>
```

(Note that this was done with libasciidoc 0.4.0... I will need  to retest against master).

**Comment by gdamore** [comment]
I see at least two issues here -- first a failure to parse the attributes on icon, and second a failure to parse the attributes on the formatted block.

I may have failed to pass -a icons -a icontype=svg to the libasciidoc run -- libasciidoc can't handle different icon formats (that's a separate failing.)

**Comment by xcoulon** [comment]
I rather believe that first, the `icon:` inline macro is not supported yet, and second, the `[.copyright2]` role on the bold text is not supported either.
I suggest we create 2 separate issues, one for each of the missing features aforementioned, and once both are implemented, we can close this one. 

Is there anything you want to work on? Otherwise, I can take care of this ;)

**Comment by xcoulon** [comment]
See https://github.com/bytesparadise/libasciidoc/issues/587 and https://github.com/bytesparadise/libasciidoc/issues/588

**Comment by gdamore** [comment]
Sounds good.  I had gone to bed already.  I am in California (San Diego area).

**Comment by xcoulon** [comment]
> Sounds good. I had gone to bed already. I am in California (San Diego area).

ok, and no worries ;)

**Comment by gdamore** [comment]
Asciidoctor does horrible here too, it turns out.  Anyway, we've opened other tickets, so we can probably close this now.
