### ISSUE TITLE
Asciidoctor extension equivalents?

### ISSUE THREAD

**Issue by bwklein** [bytesparadise/libasciidoc#592]
Hello, 

I use Asciidoctor now and use the diagram, bibtex and mathematical extensions, along with the html5s backend.

What would be the best way to use equivalents to these with libasciidoc?

**Comment by xcoulon** [comment]
hello @bwklein 👋 

I'm afraid there is no equivalent yet for these extensions, or at least nothing that I'm aware of :(

**Comment by gdamore** [comment]
We're not there yet.  But I think stuff is moving in that direction.

**Comment by xcoulon** [comment]
Well, there's https://github.com/jfeliu007/goplantuml that we could use for the PlantUML diagrams, for example.
I would have to look for other libraries for the bibtex and mathematical extensions, though.

**Comment by bwklein** [comment]
What would be the best way to develop an equivalent?  As a library or some built in capability to libasciidoc directly?

**Comment by xcoulon** [comment]
@bwklein if it's an extension for a very specific format (eg: PlantUML), I would suggest starting with a separate library which could be included in Libasciidoc as a module.

**Comment by bwklein** [comment]
Thank you

**Comment by xcoulon** [comment]
@bwklein feel free to open an issue per extension that you would need, so we know there is a demand for it, and someone can address it ;)
