### ISSUE TITLE
forum for collaboration

### ISSUE THREAD

**Issue by gdamore** [bytesparadise/libasciidoc#593]
@xcoulon -- I am thinking that as we move forward, it may be useful to have another fora for collaboration-- someplace we can discuss designs, and maybe some place where folks can ask questions and the community can assist without everything becoming a github issue.

For nanomsg (mangos, nng) I am using discord.  I use it for chat only (no voice) for my OSS projects.  There are other options, such as gitter, slack and teams.    What do you think about starting a channel for this somewhere?

I'd be happy  to do the initial setup on discord if you like.  (I started out on gitter before moving to discord, because gitter's desktop apps are basically garbage --  I didn't consider slack because for my community the barrier to entry -- an invite -- was too high, but you could decide otherwise for libasciidoc.)

My goal in this would be a form of asynchronous chat, with persistence, so we could discuss design, and coordinate some of the larger projects.

(This is filed as a github issue, because I don't actually know how better to reach you.)

**Comment by xcoulon** [comment]
yes, having a place to discuss would be very handy. As a matter of fact, GitHub announced last month during their Sateliite 2020 event a new "Discussion" feature: https://github.blog/2020-05-06-new-from-satellite-2020-github-codespaces-github-discussions-securing-code-in-private-repositories-and-more/#discussions 
However, it's in beta for now. So I wonder if we should wait a bit, hoping that it will be released soon, or use something else such as Discord as you suggested, and move to GitHub discussion later? (I like the idea of having eveything at the same place, to be honest).

**Comment by gdamore** [comment]
I've started discord here: https://discord.gg/QWKFXuF

I think we can close this for now.  I can probably arrange a more permanent and nicer URL if this is something we want to keep around for a while.
