### ISSUE TITLE
Should ID permit # and . in them?

### ISSUE THREAD

**Issue by gdamore** [bytesparadise/libasciidoc#595]
While working on #588 I discovered a possible conflict in the grammar with respect to Asciidoctor:

Shorthand markup method for assigning quoted text anchor (id) and role (Asciidoctor only)
```
[#free_the_world.big.goal]_free the world_
```

In particularly the code for ID permits # and . to be part of the ID.

As a consequence of the above shorthand rules, I conclude that these characters should not be considered legal in anchors.

However, its possible that they could be permitted when using long hand forms.

**Comment by xcoulon** [comment]
Good catch! And I wasn't aware of this shorthand syntax by the way 😬

**Comment by gdamore** [comment]
So do you think we should just prohibit them altogether, or only if they appear in an ambiguous location?  (Frankly I wish asciidoc had made this explicit.)

**Comment by gdamore** [comment]
Lots of inconsistencies, and I would not count on punctuation working at all when used in ID or role attributes.  In fact asciidoctor falls over in many ways if you inject things here.  Even whitespace is unsafe or inconsistent.

In my solution for the quoted text attributes, I workaround some of this, basically by running the strings through HTMLEscapeString.  The parser won't allow certain things, but those things don't work in asciidoctor either.

We can probably just close this ticket, since I don't think there is much more (yet ) to do here -- at least not without a formal grammar.

One thing we should probably do is a more thorough job of ensuring that everything is HTML escaped.  I have some thoughts here.  It may be that we should use html/template instead of text/template.

**Comment by xcoulon** [comment]
Ok, feel free to close this issue. I agree with you that having a formal spec would be very helpful in this particular case.

**Comment by gdamore** [comment]
Closing for now.
