### ISSUE TITLE
Refactor renderer package to allow for multiple backends

### ISSUE THREAD

**Issue by xcoulon** [bytesparadise/libasciidoc#596]
The `pkg/renderer/html5` package contains both the functions and the templates to render the document in HTML5, but these functions could certainly work for other SGML outputs such as XHTML5. 
The idea here is to separate the funcs from the templates, so that in the future, new backends would just need to provide their own templates, while reusing the already-existing funcs.

**Comment by gdamore** [comment]
Fixed by #594.
