### ISSUE TITLE
Support wanted for #mark# syntax

### ISSUE THREAD

**Issue by gdamore** [bytesparadise/libasciidoc#599]
The #mark# syntax adds markup in one of two ways.

With the default role, it looks like highlighted text.  (It uses `<mark>`.)

With a role, it uses a `<span>` element with the class matching the mark.  This allows documents to apply an arbitrary style to a range of text, which they can then control via CSS.

The solution to this should build upon the work done by #588.

**Comment by gdamore** [comment]
I added this to v0.50 for now.  Hope that's ok.  Once #588 is merged, adding this will be relatively straight-forward.

**Comment by xcoulon** [comment]
ok, sounds good to me!
