### ISSUE TITLE
Smart quotes wrong when adjacent interior space present

### ISSUE THREAD

**Issue by gdamore** [bytesparadise/libasciidoc#622]
I did some more conformance testing (was comparing other formats), and it appears that this format:

```
"` something `"
```

is wrong.   It looks like asciidoctor constrains the grammar so that interior adjacent whitespace to the rendered markup disqualifies them and they get rendered as the markup, instead of treated as smart quotes.

(I had specific test cases for this, but looking at asciidoctor it looks like I must have been confused about this.)

This is a bug, although reasonable people can disagree whether it is a bug in asciidoctor a bug in libasciidoc.  Still we should probably try to emulate the same behavior.

This appears to be limited to space characters.  Other characters like punctuation don't receive special treatment.

**Comment by gdamore** [comment]
I'll follow up with a fix for this.

**Comment by xcoulon** [comment]
ok, thanks for reporting this, @gdamore

**Comment by gdamore** [comment]
So I have a fix, but it kind of behaves differently than asciidoctor.

Asciidoctor renders "` something `" as if it is just a single string element.  The problem with our parser is that if I add logic to prevent this from being a quoted string, it turns into an attempt to render as <code> elements inside the quotes.

I think I have some ideas to adjust the parser, but to be honest I believe we wind up basically falling into a rat hole where we have different ways of handling ambiguous markup, that is honestly erroneous in the first place.

I think the original code (which allows for spaces to be inserted at the beginning or end) is actually the least deficient way to deal with this.

However, if you believe it is very important that we not diverge from asciidoctor, I can see if I can sort this out with some additional grammar elements to make the typographic elements a special string when they aren't part of smart quotes.  (This will be ordering sensitive, since that interpretation has to occur ahead of that used for monospace quoted elements.)

Anyway, just let me know what you want to do.

**Comment by xcoulon** [comment]
> Asciidoctor renders "`something`" as if it is just a single string element. The problem with our parser is that if I add logic to prevent this from being a quoted string, it turns into an attempt to render as `<code>` elements inside the quotes.

do you mean that the quoted text is parsed as monospace text within double quotes?
in that case, could it be solved by reordering some grammar rules ?

**Comment by gdamore** [comment]
Let me be clear, there are three options for rendering

```
"` word `"
```

Those are:

1.  &lquote; word &rquote;
2. `"<code> word </code>"`
3. &lquot;&backtick; word &backtick;&rquot;

Asciidoctor does what I think is the least reasonable option here, which is #3.  I presume they have created special rules to ensure that #2 is not selected.

**Comment by xcoulon** [comment]
my concern here is that until now, for all quoted texts, there was no space allowed between the surrounding marks and the enclosed text itself. Which is why I was surprised at first that something like 
```
"` word `"
```
was supported.

One quick was to prevent such spaces could be to write the rule as:
```
SingleQuotedString <- "'`" !Space elements:SingleQuotedStringElements "`'" {
    return types.NewQuotedString(types.SingleQuote, elements.([]interface{}))
}
```
and make sure that the `SingleQuotedStringElement` rule does not match content ending with a space, too.

**Comment by gdamore** [comment]
I have that much... more or less... but it turns into the second form, not the third.

I think the second form is probably the most reasonable.  I can submit a PR to do that.

**Comment by xcoulon** [comment]
hmm, no, I believe that rendering 
```
"` word `"
```
into
```
"<code> word </code>"
```
is not accurate either, because no space should be allowed between `word` and the surrounding quotes.
Why is option 3 the least reasonable to you?

**Comment by gdamore** [comment]
Option 3 means creating a special rule to detect lone cases of these two quote characters in combination, when interior space is present.  The most natural reading of the grammar is that we would instead parse the " as a lone character, and treat the interior content stuff inside backticks.

Note that 
```
`   word   `
```
is rendered as
```
<code>   word   </word>
```
by both asciidoctor and libasciidoc.  The spaces are not treated magically inside code elements.

**Comment by xcoulon** [comment]
> Option 3 means creating a special rule to detect lone cases of these two quote characters in combination, when interior space is present. The most natural reading of the grammar is that we would instead parse the " as a lone character, and treat the interior content stuff inside backticks.

I believe you could use something like
```
SingleQuotedString <- StartQuote elements:SingleQuotedStringElements EndQuote {
    return types.NewQuotedString(types.SingleQuote, elements.([]interface{}))
}

StartQuote <- "'`" !&(Space)

EndQuote <- "`'"
```
and the `SingleQuotedStringElements` rule must ensure that the last element is not a space.

Note: the `&(...)` means that you check the next tokens without "consuming" them (the parser "looks ahead"). But we could probably just use `StartQuote <- "'`" !Space` as well I guess 🤔 

> 
> Note that
> 
> ```
> `   word   `
> ```
> 
> is rendered as
> 
> ```
> <code>   word   </word>
> ```
> 
> by both asciidoctor and libasciidoc. The spaces are not treated magically inside code elements.

I did not get that result with Asciidoctor nor with Libasciidoc. Both render 
```
`   word   `
```
as
```
<div class="paragraph">
<p>`   word   `</p>
</div>
```

**Comment by gdamore** [comment]
Yes, that's correct, I forgot to include the markup.

**Comment by gdamore** [comment]
As you rules.  If I implemented what you suggested (I tried already), you get:

From
```
"`  word  `"
```

You would obtain:

```
<div class="paragraph">
<p>"<code>  word  </code>"</p>
</div>
```

However asciidoctor renders this as:

```
<div class="paragraph">
<p>"`  word  `"</p>
</div>
```

However, I'm realizing one more thing.

With asiidoctor you can use -- in limited contexts -- this:

```
mothers`' day
```

This is useful to render the curved quote when it appears at the end of the word, such as in a plural possessive.

Given that, I think we need also have some rules recognizing these typographic marks as first class entities as well.  I'll write up some more test cases.

**Comment by gdamore** [comment]
More tests:

```
mothers`' day


double-down`"

"`double-front

'`head item


tail item`'

`'

`"

"`

'`

"quoted text"`adjacent mono`
```

Result from asciidoctor (header and footer removed):

```
<div class="paragraph">
<p>mothers&#8217; day</p>
</div>
<div class="paragraph">
<p>double-down`"</p>
</div>
<div class="paragraph">
<p>"`double-front</p>
</div>
<div class="paragraph">
<p>'`head item</p>
</div>
<div class="paragraph">
<p>tail item&#8217;</p>
</div>
<div class="paragraph">
<p>&#8217;</p>
</div>
<div class="paragraph">
<p>`"</p>
</div>
<div class="paragraph">
<p>"`</p>
</div>
<div class="paragraph">
<p>'`</p>
</div>
<div class="paragraph">
<p>"quoted text"`adjacent mono`</p>
</div>
```

**Comment by gdamore** [comment]
One more
```
`adjacent mono`"quoted"
```

Result:

```
<div class="paragraph">
<p>`adjacent mono`"quoted"</p>
</div>
```

**Comment by gdamore** [comment]
From this I surmise that the monospace quoted text leaders are prohibited if there might be ambiguity with curved quotes.

**Comment by gdamore** [comment]
Using unconstrained mono like this:

```
``word``"text"
```

Does work though.  So the special rules only apply to constrained text maybe.

**Comment by gdamore** [comment]
So what I've determined is that there is an order of precedence, and there are some surprises here:

1. Smart quotes (both single and double) have highest precedence (but require no interior space before or just after the quotes, although other interior elements, such as unconstrained mono, is fine.)

2. Unconstrained monospace is next.

3. Explicit curved apostrophe - always rendered using #8217;

4. Explicit other curved marks, rendered literally

5. Single quoted monospace text

6. Lone backticks rendered literally (fallback character)


This at least is the order that asciidoctor uses, based on empirical testing.

**Comment by gdamore** [comment]
Now I've read the asciidoctor source for this.  Asciidoctor treats smart quotes as a kind of constrained quoted text.   We should probably do the same, although our handling of constrained quoted text has it's own issues.

**Comment by gdamore** [comment]
The challenges around #630 have left me completely exhausted.

I'd be happy to provide a partial fix, which fixes all but the pathological case of "`quoted`"`mono` -- asciidoctor has an implementation artifact that makes this render strangely as the mono is not considered to satisfy constraints here.  See bug #630 for the details.

Anyway, if you'd (@xcoulon ) would like me to file a PR with my partial fix (everything not pathological) I will be happy to so.  I am not interested in spending the time to rewrite pretty much the entire grammar (and probably complicating it by 2-3x) to become "bug" compatible with asciidoctor, so if that's a requirement, I'll let someone else undertake it. :-)

**Comment by xcoulon** [comment]
I see that you spent a large amount of time and energy on this issue @gdamore :( 
I don't think we should be 100% compatible with Asciidoctor and hence reproduce what seems like bugs. Let's stick to what seems reasonable to us, until we have a clarification about this part of the grammar.
So, with that in mind, I'm ok if you submit a partial PR and I will review it.
