### ISSUE TITLE
Monospace quoted text incorrect spans paragraphs

### ISSUE THREAD

**Issue by gdamore** [bytesparadise/libasciidoc#623]
I noticed that format like 

```
here is `some text

down` here
```

Winds up trying to create a `<code>` element that spans the blocks.  That's not conformant with asciidoctor, which just leaves the backticks where they are in the text.

Bold and monospace do not suffer this defect, it seems isolated to just code elements.

**Comment by gdamore** [comment]
This looks fairly trivial to solve.

```
SingleQuoteMonospaceTextElement <-  Word 
        / DoubleQuoteMonospaceText 
        / Space+ ('`' !'`')?  // allow for content such as "`some `nested monospace`". Also, do not allow for double backticks after spaces.
        / Newline // allows multiline
        / BoldText
```

That explicit listing of Newline is to blame.  I'm not sure why that was added (other quoted text forms don't have this), but I think it should be removed.

**Comment by gdamore** [comment]
Note also that newline rule is absent from the double quoted form.

**Comment by xcoulon** [comment]
Good catch!

**Comment by xcoulon** [comment]
wait, there are explicit tests for this, so this was intended: https://github.com/bytesparadise/libasciidoc/blob/master/pkg/parser/quoted_text_test.go#L1672-L1691

and both asciidoctor and libasciidoc render something like
```
`a
b`
```
into
```
<div class="paragraph">
<p><code>a
b</code></p>
</div>
```

**Comment by xcoulon** [comment]
but it works differently with your example above:
```
here is `some text

down` here
```
gives with Asciidoctor:
```
<div class="paragraph">
<p>here is `some text</p>
</div>
<div class="paragraph">
<p>down` here</p>
</div>
```
vs with Libasciidoc:
```
<div class="paragraph">
<p>here is <code>some text

down</code> here</p>
</div>  
```

**Comment by xcoulon** [comment]
I would believe that libasciidoc produces the expect output.
What do you think about it @gdamore ?

**Comment by gdamore** [comment]
I don't think <code> should span a blank line.  No other quoted text forms do.

**Comment by gdamore** [comment]
It's also the case that the double quoted form works properly.  (Well, kind of -- it falls down because of the single tick form, which it degenerates to after failing the parse.)

**Comment by gdamore** [comment]
What's interesting also is that this form does not get rendered as escaped text

```
a _italic
text_ here
```

**Comment by gdamore** [comment]
asciidoctor will honor quoted text as long as it doesn't escape the paragraph.

I think we should change the Newline rule to

/ Newline !Newline

(Meaning one newline, but not a blank link).

**Comment by xcoulon** [comment]
ah I see what you mean! Yes, indeed, the problem with 
```
here is `some text

down` here
```
is that it's actually 2 paragraphs, not one 🤦‍♂️

**Comment by xcoulon** [comment]
and indeed, similar support for a single `newline` should be part of the other quoted text rules, too.

**Comment by gdamore** [comment]
Do you want me to take this?

I'd like to fix this *before* fixing the quoting, because otherwise things get very confused.

**Comment by xcoulon** [comment]
> Do you want me to take this?
> 
> I'd like to fix this _before_ fixing the quoting, because otherwise things get very confused.

yes, please, if you have time for this. I'm still stuck with the paragraph and block substitutions for now :(
