### ISSUE TITLE
Consider using inline UTF-8 and escaping as final pass in renderer

### ISSUE THREAD

**Issue by gdamore** [bytesparadise/libasciidoc#626]
Right now we have a few places render special glyphs using unicode entities -- e.g. &#8217;

There is some inconsistency here, and I believe that there probably also some latent bugs in the treatment of these -- since it's possible for the rendering to be confused by what's meant at the parser step.

As we're moving toward using string internally (instead of []byte), I think we should just handle inline glyphs in their native UTF-8 until the final step in the rendering.

In fact, some backends have different rules, or are likely to, about what glyphs they want rendered and which they don't.  For example, the asciidoctor epub backend tends to just leave curved quotation marks in their unadulterated UTF-8, without converting them to HTML entities.  With modern HTML, this might even be preferable most of the time, as modern HTML5 requires UTF-8, so this rendering is going to be slightly faster for most users.

Probably we could use an "option" for renderers to specify whether they prefer to see non-ASCII characters turned into entities or not.

Note that entities are still required for a few special cases -- the `<`, `>`, `&`, and `"` symbols mostly.

**Comment by gdamore** [comment]
This was a pretty easy change to make... I have it in my tree, will submit a PR later.  (Mostly I want to avoid overwhelming @xcoulon with PRs... lol.)

**Comment by xcoulon** [comment]
@gdamore feel free to submit the PR ;) I'll do my best to keep up with your contribution pace (which is amazing!)
