### ISSUE TITLE
Document title should default to Untitled

### ISSUE THREAD

**Issue by gdamore** [bytesparadise/libasciidoc#627]
Noticed this when doing some comparison testing -- we don't emit the document title -- just a blank string.  Asciidoctor renders Untitled by default.  It shouldn't greatly matter, but for compatibility maybe we should set that default.

**Comment by pjanx** [comment]
I'll just argue against setting it to "Untitled" in the metadata struct, as the calling code may want to be able to detect an unset title: if you disable including the header and the footer, you need to produce your own, and you can come up with something better than Untitled, for example use the filename.

**Comment by xcoulon** [comment]
Maybe we can just set the title to `Untitled` during the HTML rendering, but keep returning an empty string to the caller, when it uses libasciidoc as a module? (ie, with the `ConvertFile` func for example)? WDYT?

**Comment by pjanx** [comment]
That seems to be what I aimed at: make the HTML renderer default to "Untitled" if it can't find a title in the document.

**Comment by xcoulon** [comment]
ok, thanks for your feedback @pjanx! I'll work on that

**Comment by xcoulon** [comment]
this should be fixed now. @pjanx please let me know if it works in your case ;)

**Comment by pjanx** [comment]
Yes, thanks.
