### ISSUE TITLE
quoted text grammar has useless ! rules

### ISSUE THREAD

**Issue by gdamore** [bytesparadise/libasciidoc#631]
In the PEG grammar, ! can exclude things not seen (tokens not consumed yet), but it cannot look backwards.

Consequently rules that use this to exclude things in the beginning of a token simply don't work if those things might have already been consumed.

For example
```
DoubleQuoteMarkedText <- attrs:(QuotedTextAttrs)? !`\\` "##" elements:(DoubleQuoteMarkedTextElements) "##" { // double punctuation must be evaluated first
```

Could be expressed equally, and better, without the attempt to exclude the leading backslash - the rule for Escaped quoted text items takes precedence, if a leading backslash is seen.

This is basically true everywhere the !`\` rules are present for quoted text.

The grammar is complex enough -- let's simplify this.

**Comment by gdamore** [comment]
PR incoming.

**Comment by xcoulon** [comment]
Good catch! Thanks @gdamore!
