### ISSUE TITLE
Consider using go generate for parser generation

### ISSUE THREAD

**Issue by gdamore** [bytesparadise/libasciidoc#638]
The current framework for this needs "make" and other tooling which makes it a bit inconvenient to work with from a Windows environment.

Using a go generate line, this would be far easier coming from a a pure Go development environment.

**Comment by moorereason** [comment]
In a similar vein, check out [`mage`](https://github.com/magefile/mage) as a pure Go replacement for `make`.  Hugo's [been using it](https://github.com/gohugoio/hugo/blob/master/magefile.go) for a few years now.

**Comment by gdamore** [comment]
I don't think "make" is ever really needed.  Go generate is more than sufficient for most cases.

**Comment by gdamore** [comment]
I have a trivial change with doc updates for this.  PR coming soon.

**Comment by xcoulon** [comment]
> I don't think "make" is ever really needed. Go generate is more than sufficient for most cases.

it is, and I intend to keep using it ;)

**Comment by gdamore** [comment]
Which are you referring to?  Make or go generate?

**Comment by xcoulon** [comment]
> Which are you referring to? Make or go generate?

`make` is my preferred choice. Take a look at the `make generate` and `make generate-optimized` goals in particular: https://github.com/bytesparadise/libasciidoc/blob/master/make/go.mk#L34-L46 
If a user wants to generate the optimized parser, she'll have to also specify all the alternate entrypoints. In this case, `make generate-optimized` is way simpler than the whole command. And entrypoints are subject to changes as we refactor the code (recently with the substitutions for example), which means that https://github.com/bytesparadise/libasciidoc/blob/master/make/go.mk is a good way to share the changes.

Again, for local testing, `go generate ./...` may be enough, but when submitting a PR, the parser will need to be built with all the required settings.

**Comment by gdamore** [comment]
Please see the updated PR.  The detailed command is part of the go generate file content.  So instead of a make file we have a generate.go.  It includes all the settings.
