### ISSUE TITLE
Use https://github.com/golangci/golangci-lint-action to speed up lint

### ISSUE THREAD

**Issue by gdamore** [bytesparadise/libasciidoc#651]
The lint dependencies are not cached properly but there is an official GitHub action from the golangci-lint folks that is optimized for performance in GitHub.

Conceivably we could also enable this to work on Windows gracefully.

**Comment by xcoulon** [comment]
I'm not sure we need to run the linter on the Windows and macOS VMs. I assume that checking the code while running on Linux is enough (and it's done for each version of Go in the matrix).

**Comment by gdamore** [comment]
Probably true, we don't have any build tags which build the code differently.
