### ISSUE TITLE
unordered lists should support style

### ISSUE THREAD

**Issue by gdamore** [bytesparadise/libasciidoc#658]
Unordered list are supposed to support the following styles

* square
* circle
* disc
* none or no-bullet (indented, but no bullet)
* unstyled (no indentation or bullet) (HTML only)

According to the docs for asciidoctor, these are placed as the class on the `<ul>` element.

**Comment by gdamore** [comment]
I'm fixing this as part of the work to generalize the parser for multiple roles.

**Comment by xcoulon** [comment]
> I'm fixing this as part of the work to generalize the parser for multiple roles.

wouldn't it be better to address this in a separate PR? It's not directly related to multiple roles on elements, is it?

**Comment by gdamore** [comment]
This will be a PR that introduces two components -- the first is the parser support (which is basically just making it use BlockAttr), and the second is the changes to the templates to actually *use* the style Attribute.

**Comment by gdamore** [comment]
Also, doing two separate PRs *substantially* increases the workload.   The PR review itself is bigger, but more to the point I have to write the tests once, and then *rewrite* (and add more) them for the follow up.  I'd just assume skip some of the middle bits.

**Comment by gdamore** [comment]
(This will be a PR with *only* the unordered list conversion though.)
