### ISSUE TITLE
Support for mdash and arrow symbols

### ISSUE THREAD

**Issue by gdamore** [bytesparadise/libasciidoc#678]
We should support two hyphens as an mdash (though apparently some prefer to render this as an ndash?) and the single  (->) and double (=>) arrows.

The latter two should probably not be substituted in literal text, but inline body text should support it.

**Comment by gdamore** [comment]
(I put this in area parser because I think we should actually recognize these symbols at *parse* time, and inject their replacements as UTF-8 values right then.  This would probably mean that no changes to the renderer are needed -- apart from test coverage.)

**Comment by gdamore** [comment]
Note also that the mdash replacement has to be sensitive to context.  See the asciidoctor docs for details.

**Comment by sdavids** [comment]
This issue is still mentioned on:

https://github.com/bytesparadise/libasciidoc/blob/master/LIMITATIONS.adoc#symbols-and-characters
