### ISSUE TITLE
Limitations list doesn't reflect the state of affairs with quoted text handling

### ISSUE THREAD

**Issue by gmarpons** [bytesparadise/libasciidoc#686]
I've just tested the tool and https://github.com/bytesparadise/libasciidoc/blob/master/LIMITATIONS.adoc#quoted-text seems out of date to me: both examples in that section work exactly as in Asciidoctor.

By the way, very good tool, congrats!

**Comment by xcoulon** [comment]
oh, looks like we need to update the doc here :) 
thanks a lot for the feedback!
