### ISSUE TITLE
Installation instructions could be more detailed

### ISSUE THREAD

**Issue by gmarpons** [bytesparadise/libasciidoc#687]
I'm talking about https://github.com/bytesparadise/libasciidoc#installation.

Proposed improvements:

- Supported go versions
- Mention pigeon as a requirement.
- Tell in which dir is `make install` to be run (for users not familiar with go).

**Comment by xcoulon** [comment]
> I'm talking about https://github.com/bytesparadise/libasciidoc#installation.
> 
> Proposed improvements:
> 
>     * Supported go versions
> 
yes, that's a good point, indeed 👍 

>     * Mention pigeon as a requirement.
pigeon should be installed by the `make install-pigeon` goal which is a transitive requirement to `make install`. Did you have to install it manually?

> 
>     * Tell in which dir is `make install` to be run (for users not familiar with go).
that's a good point, too!

**Comment by xcoulon** [comment]
and thanks for suggesting such improvements @gmarpons! 🙌

**Comment by gmarpons** [comment]
> pigeon should be installed by the make install-pigeon goal which is a transitive requirement to make install. Did you have to install it manually?

Yes. I'm on debian 10 with go 1.14 (backported). First time I ran `make install` I got an error about `pigeon` being missing. I've already lost terminal output, sorry. It's my first time installing go binaries and I didn't have a `GOPATH`, so maybe it's a problem in my system. But the default destination in Debian didn't work.

**Comment by xcoulon** [comment]
> > pigeon should be installed by the make install-pigeon goal which is a transitive requirement to make install. Did you have to install it manually?
> 
> Yes. I'm on debian 10 with go 1.14 (backported). First time I ran `make install` I got an error about `pigeon` being missing. I've already lost terminal output, sorry. It's my first time installing go binaries and I didn't have a `GOPATH`, so maybe it's a problem in my system. But the default destination in Debian didn't work.

ok, thanks for the feedback. I assumed it works but pigeon is already installed on my machine so maybe I missed something 🤔  
I'll give it a try again to make sure it works out-of-the-box ;)

**Comment by gdamore** [comment]
The average user should not need to install pigeon.  Go get should do this automatically.  (You have to use the -u flag I think).

Only developers working on modifying the source code should need to use make.

**Comment by gdamore** [comment]
I believe this is already well addressed by the changes in 70a1ec4a80e541a86c146659393b61bd67c9c9c5
