### ISSUE TITLE
Newlines in should be in templates, not renderer

### ISSUE THREAD

**Issue by gdamore** [bytesparadise/libasciidoc#699]
The renderer for SGML injects newlines between elements at various times. This is unfortunate, as it leads to extra complexity in the renderer, and leaves a portion of the generated output outside of the control of the templates.

Elements (block elements) that should have a newline appended should have that reflected in the templates, rather than having the SGML core assume this. 

I noticed this while working on an epub backend.

**Comment by xcoulon** [comment]
As far as I know, the HTML5 output is supposed to be exactly the same as Asciidoctor. Would you have any example of such a case of extra newlines?

**Comment by gdamore** [comment]
The logic implemented today leaves HTML that matches asciidoctor indeed... but it involves extra contortions and assumptions in the templates.  This ticket is a "refactor" ticket suggesting that the same output could achieved more simply by inserting the newlines in  the templates at the appropriate places (i.e. on the end of a closing block element) instead of having the logic hard coded in the renderer.

This will make for cleaner design ultimately, and leave more of the output under the control of the templates.
