### ISSUE TITLE
Source paragraph does not honor syntax highlighter

### ISSUE THREAD

**Issue by gdamore** [bytesparadise/libasciidoc#704]
We emit the highlighter ("pygments", which is a kind of lie) on the class for listingblocks that come via a source-block, but not those coming from a source-paragraph.

This is almost certainly an oversight.  (And also possibly related to #703 -- i.e. fixing #703 will probably resolve this, provided that we resolve in favor of the syntax highlighter.)

**Comment by xcoulon** [comment]
Agree with you, there are probably areas where the syntax highlighting is not supported yet 😬 

From the [the Chroma project page](https://github.com/alecthomas/chroma#chroma--a-general-purpose-syntax-highlighter-in-pure-go---): 
> Chroma is based heavily on Pygments, and includes translators for Pygments lexers and styles." 

So it's not totally a "lie" ;) And it provides compatibility with Asciidoctor.

**Comment by gdamore** [comment]
Yeah chroma seems nice, and CSS compatible with pygments.  But it's not pygments.  We probably should offer an alias of chroma -- if only to give credit where it's due to the chroma author(s).  (I'd argue that chroma should be the preferred name, pygments accepted as an alias, actually.)

**Comment by xcoulon** [comment]
yes, that's a fair point 👍  
we should clarify this and support "chroma" as a syntax highlighter choice indeed.
I'll open a separate issue for that.
