### ISSUE TITLE
Document details not parsed if document has leading newlines

### ISSUE THREAD

**Issue by gdamore** [bytesparadise/libasciidoc#707]
If a document has leading whitespace, like this:

```

= My title
Garrett D'Amore
1.0, July 4, 2020
```

The document details don't seem to be recognized.  libasciidoctor is fine with it.

**Comment by xcoulon** [comment]
what do you mean by "libasciidoctor is fine with it."?

**Comment by gdamore** [comment]
asciidoctor I meant.  Sorry.  Was late at night.

**Comment by xcoulon** [comment]
> asciidoctor I meant. Sorry. Was late at night.

no problem ;) It's what I thought too (that you meant Asciidoctor)

**Comment by xcoulon** [comment]
@gdamore sorry for the late response, I was caught with #597 and #558 🤯
