### ISSUE TITLE
version-label not honored

### ISSUE THREAD

**Issue by gdamore** [bytesparadise/libasciidoc#710]
The version label is meant to be something that can be overridden, or reset, e.g. via

:version-label!:

or

:version-label: Something Else

Note that asciidoctor does something really bizarre here, as it lower cases the supplied version label, and does not support quoting the value.  I consider that a defect in asciidoctor.

**Comment by gdamore** [comment]
The version label bug in asciidoctor was filed as https://github.com/asciidoctor/asciidoctor/issues/3709

I can see quoting the attribute label might be contentious -- but I filed that as https://github.com/asciidoctor/asciidoctor/issues/3708

These are areas where we could easily exceed asciidoctor, if we are willing to.

**Comment by xcoulon** [comment]
thanks @gdamore!
