### ISSUE TITLE
Update README.adoc

### ISSUE THREAD

**Issue by pjanx** [bytesparadise/libasciidoc#737]
E.g. `ConvertToHTML` has been replaced by `Convert`

**Comment by gdamore** [comment]
You should note that the API version is not yet 1.0.  Meaning you shouldn't count on anything with regards to compatibility.

**Comment by xcoulon** [comment]
Thanks for pointing this @pjanx and sorry if this break caused you some troubles. We're doing a lot of refactoring internally to support multiple backends, and the change from `ConvertToHTML` to `Convert` was one of the consequences (or side-effects).

**Comment by pjanx** [comment]
I understand somewhat, that's why I edited that part out later. Still, the project's been around for a while and is already fairly useful. Keeping at least minimal compatibility shims shouldn't pose much of a problem.
