### ISSUE TITLE
Can we tag v0.5.0 soon?

### ISSUE THREAD

**Issue by gdamore** [bytesparadise/libasciidoc#738]
I have consuming projects which need new functionality currently in master, and it's really a pain with go modules.  It would be a lot easier if we could tag sometime soon!

**Comment by pjanx** [comment]
Seconding, some important things have been implemented since v0.4.0 and I've been forced to do
```go get -u github.com/bytesparadise/libasciidoc@master```

**Comment by xcoulon** [comment]
it's done now: https://github.com/bytesparadise/libasciidoc/releases/tag/v0.5.0
sorry for the delay, but I got stuck with support for custom substitutions on paragraphs and delimited blocks, something I wanted to have in v0.5.0
