### ISSUE TITLE
Partially broken pass-through blocks

### ISSUE THREAD

**Issue by pjanx** [bytesparadise/libasciidoc#746]
On current master (bb8703c)
```
++++
<input>

<input>
++++
```
gives
```
&lt;input&gt;

&lt;input&gt;
```
whereas at least Asciidoctor renders it as intended.

The blank line appears to cause this issue, as removing it "fixes it".

**Comment by xcoulon** [comment]
@pjanx this should work now. 
Sorry though, I missed this issue while working on v0.5.0 🤦‍♂️

**Comment by pjanx** [comment]
Thanks, this was somewhat important to me and pass-throughs are a universal way to work around issues.

It's never too late to start using patch versions. :)

**Comment by xcoulon** [comment]
fair point! let me release a v0.5.1, then ;)

**Comment by xcoulon** [comment]
here you are: https://github.com/bytesparadise/libasciidoc/releases/tag/v0.5.1 ;)
