### ISSUE TITLE
Overzealous list item detection

### ISSUE THREAD

**Issue by pjanx** [bytesparadise/libasciidoc#747]
On current master (bb8703c)
```
- an item (quite
  short) breaks
```
gives
```
<ul>
<li>
<p>an item (quite</p>
<div class="olist lowerroman">
<ol class="lowerroman" type="i">
<li>
<p>breaks</p>
</li>
</ol>
</div>
</li>
</ul>
```

**Comment by gdamore** [comment]
I'm not sure if this is actually a "bug".  Does this break any real-world documents that are processed correctly by asciidoctor.  (It will also be interesting to see what the formal grammar specification says about this, when we have one.)

**Comment by pjanx** [comment]
It broke my real-world document, and yes, I checked against Asciidoctor before filing the issue.

It's certainly not a "lower roman" number, none of the letters are.

**Comment by xcoulon** [comment]
sorry for the late response @pjanx 
I will take a look at this issue.

**Comment by xcoulon** [comment]
@pjanx  long overdue, sorry for the delay! 
The output for your example is now
```
<div class="ulist">
<ul>
<li>
<p>an item (quite
short) breaks</p>
</li>
</ul>
</div>
```
as you would expect ;)
