### ISSUE TITLE
Reuse tests from asciidoctor?

### ISSUE THREAD

**Issue by raghur** [bytesparadise/libasciidoc#79]
What do you think about reusing tests from asciidoctor to check for compatibility? asciidoctor seems to have a rich set of tests.
While the tests are in ruby/rspec etc (I know very little of ruby myself) - but a quick pass at their tests seems to indicate that the tests go through a helper here

https://github.com/asciidoctor/asciidoctor/blob/master/test/test_helper.rb#L179

If libasciidoc had a cli exposing methods to parse document fragments, then in theory, it should be a simple matter to make the tests work.

Thoughts?

**Comment by xcoulon** [comment]
hello @raghur and thanks for suggesting this. Actually, I've been working on a CLI that is still a in a WIP here: https://github.com/bytesparadise/libasciidoc/pull/78, but I guess that could be a start. For now, I have to admin that I've been using asciidoctor to produce the `expected` output of all the tests in the `rendering/html5` package, in order to verify that the output of libasciidoc is conform to the asciidoctor "spec".

**Comment by raghur** [comment]
So I asked the [question](https://github.com/asciidoctor/asciidoctor/issues/2681) on the asciidoctor repo and their advice is to consider only the feature tests. I think it'll still be interesting to try and see how many tests fail. It'd also serve as a quantifiable way to measure completeness and I think it might help people (like me ;)) who want to contribute if there's a set failing tests that they need to make pass  to build out a asciidoc feature.

So is there anything holding up the pr #78? I'd be willing to help - but I'm quite new to Go (though not totally new)

**Comment by xcoulon** [comment]
@raghur well, for instance, I would like to add a few tests on the command. But you could probably get started before that, by pulling the code from the branch.

**Comment by raghur** [comment]
@xcoulon so I'm now able to run asciidoctor ruby tests with libasciidoc in a very hacky way :)... it's also noisy and imperfect - but you can see a log here for [text_test.rb](https://github.com/asciidoctor/asciidoctor/blob/master/test/text_test.rb)

https://pastebin.com/Nu1yQh5S
