### ISSUE TITLE
Support list item in list item continuation

### ISSUE THREAD

**Issue by xcoulon** [bytesparadise/libasciidoc#837]
Example below fails because the renderer does not expect the "chocolate" list item as a continuation
```
. cookie
+
image::cookie.png[]
+
. chocolate
+
image::chocolate.png[]
```

**Comment by bwklein** [comment]
This would be a good test for this too.

```
. In the table, enter the data shown in <<non-uniform-mesh>>
+
[#non-uniform-mesh]
.Non-Uniform Mesh Parameters
[cols="3*^",options="header"]
|===
|Dir (X,Y,Z) |Num Cells |Size
|X |10 |0.1
|Y |10 |0.1
|Y |5  |0.2
|Z |10 |0.1
|===
+
. Click *OK*
```

**Comment by xcoulon** [comment]
> This would be a good test for this too.
> 
> ```
> . In the table, enter the data shown in <<non-uniform-mesh>>
> +
> [#non-uniform-mesh]
> .Non-Uniform Mesh Parameters
> [cols="3*^",options="header"]
> |===
> |Dir (X,Y,Z) |Num Cells |Size
> |X |10 |0.1
> |Y |10 |0.1
> |Y |5  |0.2
> |Z |10 |0.1
> |===
> +
> . Click *OK*
> ```

it works now: see https://github.com/bytesparadise/libasciidoc/pull/868/files#diff-bafcc96dcdb4000d325d31b556660eac1819e49919348c0f7a33f16000ba7093R183-R246 

and thanks for suggesting this, I was able to close a few gaps while testing this case ;)

**Comment by bwklein** [comment]
@xcoulon great!  I am going to have to go back and try running some of my files through the processor.

**Comment by xcoulon** [comment]
> @xcoulon great! I am going to have to go back and try running some of my files through the processor.

@bwklein awesome! don't hesitate to open issues if you find bugs or other gaps that need to be filled!
