### ISSUE TITLE
Horizontal rules not actually supported

### ISSUE THREAD

**Issue by pjanx** [bytesparadise/libasciidoc#848]
The README claims `Horizontal rules (thematic breaks)` but [`'''`](https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/#breaks) does nothing.

**Comment by xcoulon** [comment]
thanks for reporting this @pjanx, I missed support for `'''`  🤦‍♂️ 
In the meantime, you can use the markdown-style breaks (`***`, `* * *`, `---`, `- - -`, `___`  or `_ _ _`) as defined by the grammar in https://github.com/bytesparadise/libasciidoc/blob/master/pkg/parser/parser.peg#L1632-L1634

**Comment by pjanx** [comment]
Oh, thanks, didn't know about those.
