### ISSUE TITLE
Misparsed line breaks in macro attribute lists

### ISSUE THREAD

**Issue by pjanx** [bytesparadise/libasciidoc#850]
```
link:x[
title]
```
on master produces:
```
<div class="paragraph">
<p>link:x[
title]</p>
</div>
```
but should give (Asciidoctor):
```
<div class="paragraph">
<p><a href="x">
title</a></p>
</div>
```
More of a long-time annoyance, though it'd be good to think of this during the refactoring.

**Comment by xcoulon** [comment]
thanks for reporting this issue @pjanx, I will take a look at it once I'm done with #843

**Comment by xcoulon** [comment]
```
<div class="paragraph">
<p><a href="x">
title</a></p>
</div>
```

out of curiosity, is preserving the line break between `<a href="x">` and `title` something significant for you? It doesn't see to be rendered explicitly by the browser, so I would prefer producing the following output instead:
```
<div class="paragraph">
<p><a href="x">title</a></p>
</div>
```

**Comment by pjanx** [comment]
It's all about word wrapping.

To me, this looks like normal inline content, syntactically. I wouldn't expect a line break to carry over.

**Comment by xcoulon** [comment]
ok, thanks for your feedback!

**Comment by pjanx** [comment]
Christmas is early this year.

**Comment by xcoulon** [comment]
> Christmas is early this year.

😂
