### ISSUE TITLE
Footnotes not supported in lists

### ISSUE THREAD

**Issue by pjanx** [bytesparadise/libasciidoc#851]
Hi there again.
```
 - This is a list.footnote:[And this is a footnote.]
```
gives: _unable to render full document: failed to render document elements: unable to render unordered list: unable to render unordered list item content: unable to render a list block: unable to render paragraph content: unable to render lines: unsupported type of element: types.Footnote_

**Comment by xcoulon** [comment]
hello @pjanx 

thanks for reporting this issue, I'll take a look at it as soon as I'm done with https://github.com/bytesparadise/libasciidoc/issues/843

**Comment by pjanx** [comment]
This is an area/renderer issue, rather than area/parser.

**Comment by xcoulon** [comment]
> This is an area/renderer issue, rather than area/parser.

indeed, thanks for noticing!
