### ISSUE TITLE
Support escape with backslahes

### ISSUE THREAD

**Issue by xcoulon** [bytesparadise/libasciidoc#933]
See https://docs.asciidoctor.org/asciidoc/latest/subs/prevent/

**Comment by pjanx** [comment]
Could you try to finalize 0.7.0 once you're done with this? It's been a while since the last release.

**Comment by xcoulon** [comment]
> Could you try to finalize 0.7.0 once you're done with this? It's been a while since the last release.
> 
> In passing, I'll note that LIMITATIONS.adoc is outdated now.

Sorry for the late response @pjanx :/
I want to add a few more fixes and features before releasing 0.7.0, so that parsing and rendering https://raw.githubusercontent.com/opendevise/asciidoc-samples/master/demo.adoc is the same as what Asciidoctor produces.

**Comment by xcoulon** [comment]
> In passing, I'll note that LIMITATIONS.adoc is outdated now.

Thanks, I'll open an issue for that!

**Comment by xcoulon** [comment]
> Could you try to finalize 0.7.0 once you're done with this? It's been a while since the last release.
> 
> In passing, I'll note that LIMITATIONS.adoc is outdated now.

@pjanx I just released [v0.7.0](https://github.com/bytesparadise/libasciidoc/releases/tag/v0.7.0) ;) 
And I just realised it's 1 year - 1 day since v0.6.0! 😲
