### ISSUE TITLE
Support link macros in titles

### ISSUE THREAD

**Issue by DavidGamba** [bytesparadise/libasciidoc#956]
For example:

```
.link in title https://github.com[Github]
----
content
----
```

Currently rendered as:

![image](https://user-images.githubusercontent.com/1115287/156029688-856dfcda-39a7-42b2-b25c-bb9b4d46c81d.png)

**Comment by DavidGamba** [comment]
@xcoulon this is now rendering as:

```
link in title &{map[text:Github] 0xc000095ae0}
```

**Comment by xcoulon** [comment]
oh,  my apologies, I forgot to check the rendering 🤦‍♂️ 
Let me fix that.

**Comment by xcoulon** [comment]
@DavidGamba it should [work](https://github.com/bytesparadise/libasciidoc/pull/1017/files#diff-cbaba86dbcc80b5c3e9b3341a704810aa54611a7e76e6b2c916d4c4e89a345aeR195-R205) now 😅

**Comment by DavidGamba** [comment]
That did it, thank so much!
