### ISSUE TITLE
Add WithElements interface to Section

### ISSUE THREAD

**Issue by rxt1077** [bytesparadise/libasciidoc#958]
Apologies if I'm misinterpreting or my terminology is off (this is my first time looking at golang code) but should the `Section` type support the `WithElements` interface since it has `Elements` in it? If so, I've included a simple PR based on your other code. If not, feel free to deny it and close this issue.

**Comment by xcoulon** [comment]
sure, we could add those methods, although they won't be used AFAICS

**Comment by xcoulon** [comment]
actually, I believe the methods existed before but I removed them because they were not used 🤔

**Comment by rxt1077** [comment]
Yes, they aren't currently used in the code. I was looking for a way to add plugins by passing the `Document` off to some code that walks the tree and makes substitutions. Specifically identifying taking `DelimitedBlocks` with certain attributes and making them `ImageBlocks` the way asciidoctor-diagram does. I was working on a way of visiting all elements in the `Document`.

Once again, I'm at the very early stages with nothing really to show yet. If you think it doesn't make sense to have these methods I'm sure I could implement them at the plugin level.

**Comment by xcoulon** [comment]
ok, I see! This makes sense for you to have such an interface implementation, then!
