### ISSUE TITLE
All non-ASCII Unicode is converted to HTML entities

### ISSUE THREAD

**Issue by pjanx** [bytesparadise/libasciidoc#963]
This is mildly annoying with non-Latin scripts.

See https://github.com/bytesparadise/libasciidoc/discussions/845#discussioncomment-2293279.

**Comment by xcoulon** [comment]
@pjanx please let me know if this issue is now fixed for you

**Comment by pjanx** [comment]
I believe #845 is resolved by this. And I didn't know about :unicode:, which looks like a direct answer.

**Comment by pjanx** [comment]
Oh, hey, there's a "Create issue from discussion" link.

**Comment by xcoulon** [comment]
> Oh, hey, there's a "Create issue from discussion" link. But it might only do a copy-paste.

yeah, I haven't tried it yet 🤷‍♂️

**Comment by xcoulon** [comment]
> I believe #845 is resolved by this. And I didn't know about :unicode:, which looks like a direct answer.

great, thanks for your feedback @pjanx!
