### ISSUE TITLE
Regression with curved quotation marks

### ISSUE THREAD

**Issue by pjanx** [bytesparadise/libasciidoc#972]
```
'`/`' '`\`'
```

Asciidoctor:
```
<div class="paragraph">
<p>&#8216;/&#8217; &#8216;\&#8217;</p>
</div>
```
libasciidoc:
```
<div class="paragraph">
<p>&#8216;/&#8217; '``'</p>
</div>
```

**Comment by pjanx** [comment]
Workaround:
```
'`+++\+++`'
```

**Comment by xcoulon** [comment]
thanks for reporting this issue @pjanx, I will take a look at it.

**Comment by xcoulon** [comment]
@pjanx with the refactoring done in #978, libasciidoc will render the following content:
```
'`quoted content`'
\'`escaped content\`'
'`/`' '`\`' 
'`/`' '`+++\+++`'
```
as 
```
<div class="paragraph">
<p>&#8216;quoted content&#8217;
'`escaped content`'
&#8216;/&#8217; &#8216;`'
&#8216;/&#8217; &#8216;\&#8217;</p>
</div>
```

It's still not totally on par with Asciidoctor but it's better with supporting escaped quotation marks.  
If you expect the `\` character to be surrounded by quotation marks (aka curved quotes), then the workaround you suggested above will do the trick. I hope that the upcoming Asciidoc specs can clarify a bit on the usage to the `\` character to escape those quotation marks.
